'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.5466
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace WSFD
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="ArrayOfString", [Namespace]:="https://www.foliosdigitalespac.com/WS-Folios", ItemName:="string"),  _
     System.SerializableAttribute()>  _
    Public Class ArrayOfString
        Inherits System.Collections.Generic.List(Of String)
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="https://www.foliosdigitalespac.com/WS-Folios", ConfigurationName:="WSFD.WS_FD_TFDSoap")>  _
    Public Interface WS_FD_TFDSoap
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuario del espacio de nombres https://www.foliosdigitalespac.com/WS-Folios no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="https://www.foliosdigitalespac.com/WS-Folios/TimbrarPruebaCFDI", ReplyAction:="*")>  _
        Function TimbrarPruebaCFDI(ByVal request As WSFD.TimbrarPruebaCFDIRequest) As WSFD.TimbrarPruebaCFDIResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuario del espacio de nombres https://www.foliosdigitalespac.com/WS-Folios no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="https://www.foliosdigitalespac.com/WS-Folios/TimbrarCFD", ReplyAction:="*")>  _
        Function TimbrarCFD(ByVal request As WSFD.TimbrarCFDRequest) As WSFD.TimbrarCFDResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuario del espacio de nombres https://www.foliosdigitalespac.com/WS-Folios no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="https://www.foliosdigitalespac.com/WS-Folios/CancelarCFDI", ReplyAction:="*")>  _
        Function CancelarCFDI(ByVal request As WSFD.CancelarCFDIRequest) As WSFD.CancelarCFDIResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Usuario del espacio de nombres https://www.foliosdigitalespac.com/WS-Folios no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="https://www.foliosdigitalespac.com/WS-Folios/ObtenerXML", ReplyAction:="*")>  _
        Function ObtenerXML(ByVal request As WSFD.ObtenerXMLRequest) As WSFD.ObtenerXMLResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Usuario del espacio de nombres https://www.foliosdigitalespac.com/WS-Folios no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="https://www.foliosdigitalespac.com/WS-Folios/ObtenerAcuseEnvio", ReplyAction:="*")>  _
        Function ObtenerAcuseEnvio(ByVal request As WSFD.ObtenerAcuseEnvioRequest) As WSFD.ObtenerAcuseEnvioResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Usuario del espacio de nombres https://www.foliosdigitalespac.com/WS-Folios no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="https://www.foliosdigitalespac.com/WS-Folios/ObtenerAcuseCancelacion", ReplyAction:="*")>  _
        Function ObtenerAcuseCancelacion(ByVal request As WSFD.ObtenerAcuseCancelacionRequest) As WSFD.ObtenerAcuseCancelacionResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Usuario del espacio de nombres https://www.foliosdigitalespac.com/WS-Folios no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="https://www.foliosdigitalespac.com/WS-Folios/CambiarPassword", ReplyAction:="*")>  _
        Function CambiarPassword(ByVal request As WSFD.CambiarPasswordRequest) As WSFD.CambiarPasswordResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Usuario del espacio de nombres https://www.foliosdigitalespac.com/WS-Folios no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="https://www.foliosdigitalespac.com/WS-Folios/ConsultarComplementoTimbre", ReplyAction:="*")>  _
        Function ConsultarComplementoTimbre(ByVal request As WSFD.ConsultarComplementoTimbreRequest) As WSFD.ConsultarComplementoTimbreResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Usuario del espacio de nombres https://www.foliosdigitalespac.com/WS-Folios no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="https://www.foliosdigitalespac.com/WS-Folios/ConsultarTimbrePorReferencia", ReplyAction:="*")>  _
        Function ConsultarTimbrePorReferencia(ByVal request As WSFD.ConsultarTimbrePorReferenciaRequest) As WSFD.ConsultarTimbrePorReferenciaResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Usuario del espacio de nombres https://www.foliosdigitalespac.com/WS-Folios no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="https://www.foliosdigitalespac.com/WS-Folios/ConsultarEstadoComprobante", ReplyAction:="*")>  _
        Function ConsultarEstadoComprobante(ByVal request As WSFD.ConsultarEstadoComprobanteRequest) As WSFD.ConsultarEstadoComprobanteResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Usuario del espacio de nombres https://www.foliosdigitalespac.com/WS-Folios no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="https://www.foliosdigitalespac.com/WS-Folios/ConsultarCreditos", ReplyAction:="*")>  _
        Function ConsultarCreditos(ByVal request As WSFD.ConsultarCreditosRequest) As WSFD.ConsultarCreditosResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class TimbrarPruebaCFDIRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="TimbrarPruebaCFDI", [Namespace]:="https://www.foliosdigitalespac.com/WS-Folios", Order:=0)>  _
        Public Body As WSFD.TimbrarPruebaCFDIRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSFD.TimbrarPruebaCFDIRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://www.foliosdigitalespac.com/WS-Folios")>  _
    Partial Public Class TimbrarPruebaCFDIRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public usuario As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public password As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public cadenaXML As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal usuario As String, ByVal password As String, ByVal cadenaXML As String)
            MyBase.New
            Me.usuario = usuario
            Me.password = password
            Me.cadenaXML = cadenaXML
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class TimbrarPruebaCFDIResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="TimbrarPruebaCFDIResponse", [Namespace]:="https://www.foliosdigitalespac.com/WS-Folios", Order:=0)>  _
        Public Body As WSFD.TimbrarPruebaCFDIResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSFD.TimbrarPruebaCFDIResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://www.foliosdigitalespac.com/WS-Folios")>  _
    Partial Public Class TimbrarPruebaCFDIResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public TimbrarPruebaCFDIResult As WSFD.ArrayOfString
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal TimbrarPruebaCFDIResult As WSFD.ArrayOfString)
            MyBase.New
            Me.TimbrarPruebaCFDIResult = TimbrarPruebaCFDIResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class TimbrarCFDRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="TimbrarCFD", [Namespace]:="https://www.foliosdigitalespac.com/WS-Folios", Order:=0)>  _
        Public Body As WSFD.TimbrarCFDRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSFD.TimbrarCFDRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://www.foliosdigitalespac.com/WS-Folios")>  _
    Partial Public Class TimbrarCFDRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public usuario As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public password As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public cadenaXML As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public referencia As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal usuario As String, ByVal password As String, ByVal cadenaXML As String, ByVal referencia As String)
            MyBase.New
            Me.usuario = usuario
            Me.password = password
            Me.cadenaXML = cadenaXML
            Me.referencia = referencia
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class TimbrarCFDResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="TimbrarCFDResponse", [Namespace]:="https://www.foliosdigitalespac.com/WS-Folios", Order:=0)>  _
        Public Body As WSFD.TimbrarCFDResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSFD.TimbrarCFDResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://www.foliosdigitalespac.com/WS-Folios")>  _
    Partial Public Class TimbrarCFDResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public TimbrarCFDResult As WSFD.ArrayOfString
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal TimbrarCFDResult As WSFD.ArrayOfString)
            MyBase.New
            Me.TimbrarCFDResult = TimbrarCFDResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class CancelarCFDIRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="CancelarCFDI", [Namespace]:="https://www.foliosdigitalespac.com/WS-Folios", Order:=0)>  _
        Public Body As WSFD.CancelarCFDIRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSFD.CancelarCFDIRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://www.foliosdigitalespac.com/WS-Folios")>  _
    Partial Public Class CancelarCFDIRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public usuario As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public password As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public RFCEmisor As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public listaCFDI As WSFD.ArrayOfString
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public certificadoPKCS12_Base64 As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public passwordPKCS12 As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal usuario As String, ByVal password As String, ByVal RFCEmisor As String, ByVal listaCFDI As WSFD.ArrayOfString, ByVal certificadoPKCS12_Base64 As String, ByVal passwordPKCS12 As String)
            MyBase.New
            Me.usuario = usuario
            Me.password = password
            Me.RFCEmisor = RFCEmisor
            Me.listaCFDI = listaCFDI
            Me.certificadoPKCS12_Base64 = certificadoPKCS12_Base64
            Me.passwordPKCS12 = passwordPKCS12
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class CancelarCFDIResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="CancelarCFDIResponse", [Namespace]:="https://www.foliosdigitalespac.com/WS-Folios", Order:=0)>  _
        Public Body As WSFD.CancelarCFDIResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSFD.CancelarCFDIResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://www.foliosdigitalespac.com/WS-Folios")>  _
    Partial Public Class CancelarCFDIResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public CancelarCFDIResult As WSFD.ArrayOfString
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal CancelarCFDIResult As WSFD.ArrayOfString)
            MyBase.New
            Me.CancelarCFDIResult = CancelarCFDIResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ObtenerXMLRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ObtenerXML", [Namespace]:="https://www.foliosdigitalespac.com/WS-Folios", Order:=0)>  _
        Public Body As WSFD.ObtenerXMLRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSFD.ObtenerXMLRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://www.foliosdigitalespac.com/WS-Folios")>  _
    Partial Public Class ObtenerXMLRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public Usuario As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Password As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public UUID As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public RFCEmisor As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Usuario As String, ByVal Password As String, ByVal UUID As String, ByVal RFCEmisor As String)
            MyBase.New
            Me.Usuario = Usuario
            Me.Password = Password
            Me.UUID = UUID
            Me.RFCEmisor = RFCEmisor
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ObtenerXMLResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ObtenerXMLResponse", [Namespace]:="https://www.foliosdigitalespac.com/WS-Folios", Order:=0)>  _
        Public Body As WSFD.ObtenerXMLResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSFD.ObtenerXMLResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://www.foliosdigitalespac.com/WS-Folios")>  _
    Partial Public Class ObtenerXMLResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ObtenerXMLResult As WSFD.ArrayOfString
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ObtenerXMLResult As WSFD.ArrayOfString)
            MyBase.New
            Me.ObtenerXMLResult = ObtenerXMLResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ObtenerAcuseEnvioRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ObtenerAcuseEnvio", [Namespace]:="https://www.foliosdigitalespac.com/WS-Folios", Order:=0)>  _
        Public Body As WSFD.ObtenerAcuseEnvioRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSFD.ObtenerAcuseEnvioRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://www.foliosdigitalespac.com/WS-Folios")>  _
    Partial Public Class ObtenerAcuseEnvioRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public Usuario As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Password As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public UUID As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public RFCEmisor As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Usuario As String, ByVal Password As String, ByVal UUID As String, ByVal RFCEmisor As String)
            MyBase.New
            Me.Usuario = Usuario
            Me.Password = Password
            Me.UUID = UUID
            Me.RFCEmisor = RFCEmisor
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ObtenerAcuseEnvioResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ObtenerAcuseEnvioResponse", [Namespace]:="https://www.foliosdigitalespac.com/WS-Folios", Order:=0)>  _
        Public Body As WSFD.ObtenerAcuseEnvioResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSFD.ObtenerAcuseEnvioResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://www.foliosdigitalespac.com/WS-Folios")>  _
    Partial Public Class ObtenerAcuseEnvioResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ObtenerAcuseEnvioResult As WSFD.ArrayOfString
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ObtenerAcuseEnvioResult As WSFD.ArrayOfString)
            MyBase.New
            Me.ObtenerAcuseEnvioResult = ObtenerAcuseEnvioResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ObtenerAcuseCancelacionRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ObtenerAcuseCancelacion", [Namespace]:="https://www.foliosdigitalespac.com/WS-Folios", Order:=0)>  _
        Public Body As WSFD.ObtenerAcuseCancelacionRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSFD.ObtenerAcuseCancelacionRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://www.foliosdigitalespac.com/WS-Folios")>  _
    Partial Public Class ObtenerAcuseCancelacionRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public Usuario As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Password As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public UUID As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public RFCEmisor As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Usuario As String, ByVal Password As String, ByVal UUID As String, ByVal RFCEmisor As String)
            MyBase.New
            Me.Usuario = Usuario
            Me.Password = Password
            Me.UUID = UUID
            Me.RFCEmisor = RFCEmisor
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ObtenerAcuseCancelacionResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ObtenerAcuseCancelacionResponse", [Namespace]:="https://www.foliosdigitalespac.com/WS-Folios", Order:=0)>  _
        Public Body As WSFD.ObtenerAcuseCancelacionResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSFD.ObtenerAcuseCancelacionResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://www.foliosdigitalespac.com/WS-Folios")>  _
    Partial Public Class ObtenerAcuseCancelacionResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ObtenerAcuseCancelacionResult As WSFD.ArrayOfString
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ObtenerAcuseCancelacionResult As WSFD.ArrayOfString)
            MyBase.New
            Me.ObtenerAcuseCancelacionResult = ObtenerAcuseCancelacionResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class CambiarPasswordRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="CambiarPassword", [Namespace]:="https://www.foliosdigitalespac.com/WS-Folios", Order:=0)>  _
        Public Body As WSFD.CambiarPasswordRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSFD.CambiarPasswordRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://www.foliosdigitalespac.com/WS-Folios")>  _
    Partial Public Class CambiarPasswordRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public Usuario As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public passwordActual As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public passwordNuevo As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Usuario As String, ByVal passwordActual As String, ByVal passwordNuevo As String)
            MyBase.New
            Me.Usuario = Usuario
            Me.passwordActual = passwordActual
            Me.passwordNuevo = passwordNuevo
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class CambiarPasswordResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="CambiarPasswordResponse", [Namespace]:="https://www.foliosdigitalespac.com/WS-Folios", Order:=0)>  _
        Public Body As WSFD.CambiarPasswordResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSFD.CambiarPasswordResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://www.foliosdigitalespac.com/WS-Folios")>  _
    Partial Public Class CambiarPasswordResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public CambiarPasswordResult As WSFD.ArrayOfString
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal CambiarPasswordResult As WSFD.ArrayOfString)
            MyBase.New
            Me.CambiarPasswordResult = CambiarPasswordResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ConsultarComplementoTimbreRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ConsultarComplementoTimbre", [Namespace]:="https://www.foliosdigitalespac.com/WS-Folios", Order:=0)>  _
        Public Body As WSFD.ConsultarComplementoTimbreRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSFD.ConsultarComplementoTimbreRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://www.foliosdigitalespac.com/WS-Folios")>  _
    Partial Public Class ConsultarComplementoTimbreRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public Usuario As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Password As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public UUID As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Usuario As String, ByVal Password As String, ByVal UUID As String)
            MyBase.New
            Me.Usuario = Usuario
            Me.Password = Password
            Me.UUID = UUID
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ConsultarComplementoTimbreResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ConsultarComplementoTimbreResponse", [Namespace]:="https://www.foliosdigitalespac.com/WS-Folios", Order:=0)>  _
        Public Body As WSFD.ConsultarComplementoTimbreResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSFD.ConsultarComplementoTimbreResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://www.foliosdigitalespac.com/WS-Folios")>  _
    Partial Public Class ConsultarComplementoTimbreResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ConsultarComplementoTimbreResult As WSFD.ArrayOfString
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ConsultarComplementoTimbreResult As WSFD.ArrayOfString)
            MyBase.New
            Me.ConsultarComplementoTimbreResult = ConsultarComplementoTimbreResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ConsultarTimbrePorReferenciaRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ConsultarTimbrePorReferencia", [Namespace]:="https://www.foliosdigitalespac.com/WS-Folios", Order:=0)>  _
        Public Body As WSFD.ConsultarTimbrePorReferenciaRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSFD.ConsultarTimbrePorReferenciaRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://www.foliosdigitalespac.com/WS-Folios")>  _
    Partial Public Class ConsultarTimbrePorReferenciaRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public Usuario As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Password As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public RFCEmisor As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Referencia As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Usuario As String, ByVal Password As String, ByVal RFCEmisor As String, ByVal Referencia As String)
            MyBase.New
            Me.Usuario = Usuario
            Me.Password = Password
            Me.RFCEmisor = RFCEmisor
            Me.Referencia = Referencia
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ConsultarTimbrePorReferenciaResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ConsultarTimbrePorReferenciaResponse", [Namespace]:="https://www.foliosdigitalespac.com/WS-Folios", Order:=0)>  _
        Public Body As WSFD.ConsultarTimbrePorReferenciaResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSFD.ConsultarTimbrePorReferenciaResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://www.foliosdigitalespac.com/WS-Folios")>  _
    Partial Public Class ConsultarTimbrePorReferenciaResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ConsultarTimbrePorReferenciaResult As WSFD.ArrayOfString
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ConsultarTimbrePorReferenciaResult As WSFD.ArrayOfString)
            MyBase.New
            Me.ConsultarTimbrePorReferenciaResult = ConsultarTimbrePorReferenciaResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ConsultarEstadoComprobanteRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ConsultarEstadoComprobante", [Namespace]:="https://www.foliosdigitalespac.com/WS-Folios", Order:=0)>  _
        Public Body As WSFD.ConsultarEstadoComprobanteRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSFD.ConsultarEstadoComprobanteRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://www.foliosdigitalespac.com/WS-Folios")>  _
    Partial Public Class ConsultarEstadoComprobanteRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public Usuario As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Password As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public UUID As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Usuario As String, ByVal Password As String, ByVal UUID As String)
            MyBase.New
            Me.Usuario = Usuario
            Me.Password = Password
            Me.UUID = UUID
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ConsultarEstadoComprobanteResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ConsultarEstadoComprobanteResponse", [Namespace]:="https://www.foliosdigitalespac.com/WS-Folios", Order:=0)>  _
        Public Body As WSFD.ConsultarEstadoComprobanteResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSFD.ConsultarEstadoComprobanteResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://www.foliosdigitalespac.com/WS-Folios")>  _
    Partial Public Class ConsultarEstadoComprobanteResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ConsultarEstadoComprobanteResult As WSFD.ArrayOfString
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ConsultarEstadoComprobanteResult As WSFD.ArrayOfString)
            MyBase.New
            Me.ConsultarEstadoComprobanteResult = ConsultarEstadoComprobanteResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ConsultarCreditosRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ConsultarCreditos", [Namespace]:="https://www.foliosdigitalespac.com/WS-Folios", Order:=0)>  _
        Public Body As WSFD.ConsultarCreditosRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSFD.ConsultarCreditosRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://www.foliosdigitalespac.com/WS-Folios")>  _
    Partial Public Class ConsultarCreditosRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public Usuario As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Password As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Usuario As String, ByVal Password As String)
            MyBase.New
            Me.Usuario = Usuario
            Me.Password = Password
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ConsultarCreditosResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ConsultarCreditosResponse", [Namespace]:="https://www.foliosdigitalespac.com/WS-Folios", Order:=0)>  _
        Public Body As WSFD.ConsultarCreditosResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSFD.ConsultarCreditosResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="https://www.foliosdigitalespac.com/WS-Folios")>  _
    Partial Public Class ConsultarCreditosResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ConsultarCreditosResult As WSFD.ArrayOfString
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ConsultarCreditosResult As WSFD.ArrayOfString)
            MyBase.New
            Me.ConsultarCreditosResult = ConsultarCreditosResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Public Interface WS_FD_TFDSoapChannel
        Inherits WSFD.WS_FD_TFDSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Partial Public Class WS_FD_TFDSoapClient
        Inherits System.ServiceModel.ClientBase(Of WSFD.WS_FD_TFDSoap)
        Implements WSFD.WS_FD_TFDSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSFD_WS_FD_TFDSoap_TimbrarPruebaCFDI(ByVal request As WSFD.TimbrarPruebaCFDIRequest) As WSFD.TimbrarPruebaCFDIResponse Implements WSFD.WS_FD_TFDSoap.TimbrarPruebaCFDI
            Return MyBase.Channel.TimbrarPruebaCFDI(request)
        End Function
        
        Public Function TimbrarPruebaCFDI(ByVal usuario As String, ByVal password As String, ByVal cadenaXML As String) As WSFD.ArrayOfString
            Dim inValue As WSFD.TimbrarPruebaCFDIRequest = New WSFD.TimbrarPruebaCFDIRequest
            inValue.Body = New WSFD.TimbrarPruebaCFDIRequestBody
            inValue.Body.usuario = usuario
            inValue.Body.password = password
            inValue.Body.cadenaXML = cadenaXML
            Dim retVal As WSFD.TimbrarPruebaCFDIResponse = CType(Me,WSFD.WS_FD_TFDSoap).TimbrarPruebaCFDI(inValue)
            Return retVal.Body.TimbrarPruebaCFDIResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSFD_WS_FD_TFDSoap_TimbrarCFD(ByVal request As WSFD.TimbrarCFDRequest) As WSFD.TimbrarCFDResponse Implements WSFD.WS_FD_TFDSoap.TimbrarCFD
            Return MyBase.Channel.TimbrarCFD(request)
        End Function
        
        Public Function TimbrarCFD(ByVal usuario As String, ByVal password As String, ByVal cadenaXML As String, ByVal referencia As String) As WSFD.ArrayOfString
            Dim inValue As WSFD.TimbrarCFDRequest = New WSFD.TimbrarCFDRequest
            inValue.Body = New WSFD.TimbrarCFDRequestBody
            inValue.Body.usuario = usuario
            inValue.Body.password = password
            inValue.Body.cadenaXML = cadenaXML
            inValue.Body.referencia = referencia
            Dim retVal As WSFD.TimbrarCFDResponse = CType(Me,WSFD.WS_FD_TFDSoap).TimbrarCFD(inValue)
            Return retVal.Body.TimbrarCFDResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSFD_WS_FD_TFDSoap_CancelarCFDI(ByVal request As WSFD.CancelarCFDIRequest) As WSFD.CancelarCFDIResponse Implements WSFD.WS_FD_TFDSoap.CancelarCFDI
            Return MyBase.Channel.CancelarCFDI(request)
        End Function
        
        Public Function CancelarCFDI(ByVal usuario As String, ByVal password As String, ByVal RFCEmisor As String, ByVal listaCFDI As WSFD.ArrayOfString, ByVal certificadoPKCS12_Base64 As String, ByVal passwordPKCS12 As String) As WSFD.ArrayOfString
            Dim inValue As WSFD.CancelarCFDIRequest = New WSFD.CancelarCFDIRequest
            inValue.Body = New WSFD.CancelarCFDIRequestBody
            inValue.Body.usuario = usuario
            inValue.Body.password = password
            inValue.Body.RFCEmisor = RFCEmisor
            inValue.Body.listaCFDI = listaCFDI
            inValue.Body.certificadoPKCS12_Base64 = certificadoPKCS12_Base64
            inValue.Body.passwordPKCS12 = passwordPKCS12
            Dim retVal As WSFD.CancelarCFDIResponse = CType(Me,WSFD.WS_FD_TFDSoap).CancelarCFDI(inValue)
            Return retVal.Body.CancelarCFDIResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSFD_WS_FD_TFDSoap_ObtenerXML(ByVal request As WSFD.ObtenerXMLRequest) As WSFD.ObtenerXMLResponse Implements WSFD.WS_FD_TFDSoap.ObtenerXML
            Return MyBase.Channel.ObtenerXML(request)
        End Function
        
        Public Function ObtenerXML(ByVal Usuario As String, ByVal Password As String, ByVal UUID As String, ByVal RFCEmisor As String) As WSFD.ArrayOfString
            Dim inValue As WSFD.ObtenerXMLRequest = New WSFD.ObtenerXMLRequest
            inValue.Body = New WSFD.ObtenerXMLRequestBody
            inValue.Body.Usuario = Usuario
            inValue.Body.Password = Password
            inValue.Body.UUID = UUID
            inValue.Body.RFCEmisor = RFCEmisor
            Dim retVal As WSFD.ObtenerXMLResponse = CType(Me,WSFD.WS_FD_TFDSoap).ObtenerXML(inValue)
            Return retVal.Body.ObtenerXMLResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSFD_WS_FD_TFDSoap_ObtenerAcuseEnvio(ByVal request As WSFD.ObtenerAcuseEnvioRequest) As WSFD.ObtenerAcuseEnvioResponse Implements WSFD.WS_FD_TFDSoap.ObtenerAcuseEnvio
            Return MyBase.Channel.ObtenerAcuseEnvio(request)
        End Function
        
        Public Function ObtenerAcuseEnvio(ByVal Usuario As String, ByVal Password As String, ByVal UUID As String, ByVal RFCEmisor As String) As WSFD.ArrayOfString
            Dim inValue As WSFD.ObtenerAcuseEnvioRequest = New WSFD.ObtenerAcuseEnvioRequest
            inValue.Body = New WSFD.ObtenerAcuseEnvioRequestBody
            inValue.Body.Usuario = Usuario
            inValue.Body.Password = Password
            inValue.Body.UUID = UUID
            inValue.Body.RFCEmisor = RFCEmisor
            Dim retVal As WSFD.ObtenerAcuseEnvioResponse = CType(Me,WSFD.WS_FD_TFDSoap).ObtenerAcuseEnvio(inValue)
            Return retVal.Body.ObtenerAcuseEnvioResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSFD_WS_FD_TFDSoap_ObtenerAcuseCancelacion(ByVal request As WSFD.ObtenerAcuseCancelacionRequest) As WSFD.ObtenerAcuseCancelacionResponse Implements WSFD.WS_FD_TFDSoap.ObtenerAcuseCancelacion
            Return MyBase.Channel.ObtenerAcuseCancelacion(request)
        End Function
        
        Public Function ObtenerAcuseCancelacion(ByVal Usuario As String, ByVal Password As String, ByVal UUID As String, ByVal RFCEmisor As String) As WSFD.ArrayOfString
            Dim inValue As WSFD.ObtenerAcuseCancelacionRequest = New WSFD.ObtenerAcuseCancelacionRequest
            inValue.Body = New WSFD.ObtenerAcuseCancelacionRequestBody
            inValue.Body.Usuario = Usuario
            inValue.Body.Password = Password
            inValue.Body.UUID = UUID
            inValue.Body.RFCEmisor = RFCEmisor
            Dim retVal As WSFD.ObtenerAcuseCancelacionResponse = CType(Me,WSFD.WS_FD_TFDSoap).ObtenerAcuseCancelacion(inValue)
            Return retVal.Body.ObtenerAcuseCancelacionResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSFD_WS_FD_TFDSoap_CambiarPassword(ByVal request As WSFD.CambiarPasswordRequest) As WSFD.CambiarPasswordResponse Implements WSFD.WS_FD_TFDSoap.CambiarPassword
            Return MyBase.Channel.CambiarPassword(request)
        End Function
        
        Public Function CambiarPassword(ByVal Usuario As String, ByVal passwordActual As String, ByVal passwordNuevo As String) As WSFD.ArrayOfString
            Dim inValue As WSFD.CambiarPasswordRequest = New WSFD.CambiarPasswordRequest
            inValue.Body = New WSFD.CambiarPasswordRequestBody
            inValue.Body.Usuario = Usuario
            inValue.Body.passwordActual = passwordActual
            inValue.Body.passwordNuevo = passwordNuevo
            Dim retVal As WSFD.CambiarPasswordResponse = CType(Me,WSFD.WS_FD_TFDSoap).CambiarPassword(inValue)
            Return retVal.Body.CambiarPasswordResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSFD_WS_FD_TFDSoap_ConsultarComplementoTimbre(ByVal request As WSFD.ConsultarComplementoTimbreRequest) As WSFD.ConsultarComplementoTimbreResponse Implements WSFD.WS_FD_TFDSoap.ConsultarComplementoTimbre
            Return MyBase.Channel.ConsultarComplementoTimbre(request)
        End Function
        
        Public Function ConsultarComplementoTimbre(ByVal Usuario As String, ByVal Password As String, ByVal UUID As String) As WSFD.ArrayOfString
            Dim inValue As WSFD.ConsultarComplementoTimbreRequest = New WSFD.ConsultarComplementoTimbreRequest
            inValue.Body = New WSFD.ConsultarComplementoTimbreRequestBody
            inValue.Body.Usuario = Usuario
            inValue.Body.Password = Password
            inValue.Body.UUID = UUID
            Dim retVal As WSFD.ConsultarComplementoTimbreResponse = CType(Me,WSFD.WS_FD_TFDSoap).ConsultarComplementoTimbre(inValue)
            Return retVal.Body.ConsultarComplementoTimbreResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSFD_WS_FD_TFDSoap_ConsultarTimbrePorReferencia(ByVal request As WSFD.ConsultarTimbrePorReferenciaRequest) As WSFD.ConsultarTimbrePorReferenciaResponse Implements WSFD.WS_FD_TFDSoap.ConsultarTimbrePorReferencia
            Return MyBase.Channel.ConsultarTimbrePorReferencia(request)
        End Function
        
        Public Function ConsultarTimbrePorReferencia(ByVal Usuario As String, ByVal Password As String, ByVal RFCEmisor As String, ByVal Referencia As String) As WSFD.ArrayOfString
            Dim inValue As WSFD.ConsultarTimbrePorReferenciaRequest = New WSFD.ConsultarTimbrePorReferenciaRequest
            inValue.Body = New WSFD.ConsultarTimbrePorReferenciaRequestBody
            inValue.Body.Usuario = Usuario
            inValue.Body.Password = Password
            inValue.Body.RFCEmisor = RFCEmisor
            inValue.Body.Referencia = Referencia
            Dim retVal As WSFD.ConsultarTimbrePorReferenciaResponse = CType(Me,WSFD.WS_FD_TFDSoap).ConsultarTimbrePorReferencia(inValue)
            Return retVal.Body.ConsultarTimbrePorReferenciaResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSFD_WS_FD_TFDSoap_ConsultarEstadoComprobante(ByVal request As WSFD.ConsultarEstadoComprobanteRequest) As WSFD.ConsultarEstadoComprobanteResponse Implements WSFD.WS_FD_TFDSoap.ConsultarEstadoComprobante
            Return MyBase.Channel.ConsultarEstadoComprobante(request)
        End Function
        
        Public Function ConsultarEstadoComprobante(ByVal Usuario As String, ByVal Password As String, ByVal UUID As String) As WSFD.ArrayOfString
            Dim inValue As WSFD.ConsultarEstadoComprobanteRequest = New WSFD.ConsultarEstadoComprobanteRequest
            inValue.Body = New WSFD.ConsultarEstadoComprobanteRequestBody
            inValue.Body.Usuario = Usuario
            inValue.Body.Password = Password
            inValue.Body.UUID = UUID
            Dim retVal As WSFD.ConsultarEstadoComprobanteResponse = CType(Me,WSFD.WS_FD_TFDSoap).ConsultarEstadoComprobante(inValue)
            Return retVal.Body.ConsultarEstadoComprobanteResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSFD_WS_FD_TFDSoap_ConsultarCreditos(ByVal request As WSFD.ConsultarCreditosRequest) As WSFD.ConsultarCreditosResponse Implements WSFD.WS_FD_TFDSoap.ConsultarCreditos
            Return MyBase.Channel.ConsultarCreditos(request)
        End Function
        
        Public Function ConsultarCreditos(ByVal Usuario As String, ByVal Password As String) As WSFD.ArrayOfString
            Dim inValue As WSFD.ConsultarCreditosRequest = New WSFD.ConsultarCreditosRequest
            inValue.Body = New WSFD.ConsultarCreditosRequestBody
            inValue.Body.Usuario = Usuario
            inValue.Body.Password = Password
            Dim retVal As WSFD.ConsultarCreditosResponse = CType(Me,WSFD.WS_FD_TFDSoap).ConsultarCreditos(inValue)
            Return retVal.Body.ConsultarCreditosResult
        End Function
    End Class
End Namespace
