'
''
''  Agrupacion.vb
''  Implementation of the Class Agrupacion
''  Generated by Enterprise Architect
''  Created on:      23-Sep-2008 10:36:56 a.m.
''  Original author: 
''  
''
''  Modification history:
''  
''
'



Namespace Comunes.Comun
    Public Class ClsAgrupacion
        Inherits ClsBaseComun


        Private atrCampo As ClsCampos
        Private atrOrden As Integer


        Public Property Campo() As ClsCampos
            Get
                Return atrCampo
            End Get
            Set(ByVal value As ClsCampos)
                atrCampo = value
            End Set
        End Property


        Public Property Orden() As Integer
            Get
                Return atrOrden
            End Get
            Set(ByVal value As Integer)
                atrOrden = value
            End Set
        End Property


        Public Overrides Function FormatoFolio() As String
            Return ""
        End Function

        Public Overrides Function getNombreFolioAdministrado() As String
            Return ""
        End Function

        Public Overrides Function getRow() As ClsBaseComun.ObtenerRowEventHandler
            Return Nothing
        End Function
    End Class ' Agrupacion
End Namespace