'
''
''  Campos.vb
''  Implementation of the Class Campos
''  Generated by Enterprise Architect
''  Created on:      23-Sep-2008 10:37:50 a.m.
''  Original author: 
''  
'
''  Modification history:
''  
''
'


Namespace Comunes.Comun
    Public Class ClsCampos
        Inherits ClsBaseComun

        Private atrNombre As String
        Private atrTipo As String



        Public Property Nombre() As String
            Get
                Return atrNombre
            End Get
            Set(ByVal value As String)
                atrNombre = value
            End Set
        End Property


        Public Property Tipo() As String
            Get
                Return atrTipo
            End Get
            Set(ByVal value As String)
                atrTipo = value
            End Set
        End Property


        Public Overrides Function FormatoFolio() As String
            Return ""
        End Function

        Public Overrides Function getNombreFolioAdministrado() As String
            Return ""
        End Function

        Public Overrides Function getRow() As ClsBaseComun.ObtenerRowEventHandler
            Return Nothing
        End Function
    End Class ' Campos
End Namespace
