'
''
''  Columnas.vb
''  Implementation of the Class Columnas
''  Generated by Enterprise Architect
''  Created on:      23-Sep-2008 10:38:04 a.m.
''  Original author: 
''  
'
''  Modification history:
''  
''
'



Namespace Comunes.Comun
    Public Class ClsColumnas
        Inherits ClsBaseComun

        Private atrCampo As ClsCampos
        Private atrAncho As Integer
        Private atrOrden As Integer
        Private atrFormato As String

        Public Property Campo() As ClsCampos
            Get
                Return atrCampo
            End Get
            Set(ByVal value As ClsCampos)
                atrCampo = value
            End Set
        End Property

        Public Property Ancho() As Integer
            Get
                Return atrAncho
            End Get
            Set(ByVal value As Integer)
                atrAncho = value
            End Set
        End Property

        Public Property Orden() As Integer
            Get
                Return atrOrden
            End Get
            Set(ByVal value As Integer)
                atrOrden = value
            End Set
        End Property

        Public Property Formato() As String
            Get
                Return atrFormato
            End Get
            Set(ByVal value As String)
                atrFormato = value
            End Set
        End Property

        Public Overrides Function FormatoFolio() As String
            Return ""
        End Function

        Public Overrides Function getNombreFolioAdministrado() As String
            Return ""
        End Function

        Public Overrides Function getRow() As ClsBaseComun.ObtenerRowEventHandler
            Return Nothing
        End Function
    End Class ' Columnas
End Namespace
