'
''
''  reportes.vb
''  Implementation of the Class Ordenacion
''  Generated by Enterprise Architect
''  Created on:      23-Sep-2008 10:18:57 a.m.
''  Original author: 
''  
'
''  Modification history:
''  
''
'

Imports System.Xml.Serialization
Imports Access

Namespace Comunes.Comun
    <Serializable()> _
    Public Class ClsReportes
        Inherits ClsBaseComun
        Implements IXmlSerializable

        Private atrStore As String
        Private atrQuery As String
        Private atrFrom As String
        Private atrWhere As String
        Private atrGroup As String
        Private atrOrder As String
        Private atrHaving As String
        Private atrCampos() As ClsCampos
        Private atrColumnas() As ClsColumnas
        Private atrAgrupacion() As ClsAgrupacion
        Private atrEncabezados() As String
        Private atrOrdenacion() As ClsOrdenacion
        Private atrPiesPagina() As String
        Private atrFiltros() As ClsFiltros
        Private atrTotales() As ClsTotales
        Private atrModificaColumnas As Boolean
        Private atrNombreReporte As String
        Private atrModificaAgrupacion As Boolean
        Private atrModificaOrdenacion As Boolean
        Private atrModificaTotales As Boolean
        Private atrCamposGlobal As ClsCamposGlobal
        Private atrFiltrosGlobal As ClsFiltrosGlobal
        Private atrCalculaAcumulado As Boolean
        Private atrCampoRelativo As String
        Private atrCampoAcumulado As String
        Private atrClasificadores As String
        Private atrOmitirAlias As Boolean

        Public dtFormatos As New DataTable

        Public Property Clasificadores() As String
            Get
                Return atrClasificadores
            End Get
            Set(ByVal value As String)
                atrClasificadores = value
            End Set
        End Property

        Public Property Store() As String
            Get
                Return atrStore
            End Get
            Set(ByVal value As String)
                atrStore = value
            End Set
        End Property

        Public Property CalculaAcumulado() As Boolean
            Get
                Return atrCalculaAcumulado
            End Get
            Set(ByVal value As Boolean)
                atrCalculaAcumulado = value
            End Set
        End Property

        Public Property CampoRelativo() As String
            Get
                Return atrCampoRelativo
            End Get
            Set(ByVal value As String)
                atrCampoRelativo = value
            End Set
        End Property

        Public Property CampoAcumulado() As String
            Get
                Return atrCampoAcumulado
            End Get
            Set(ByVal value As String)
                atrCampoAcumulado = value
            End Set
        End Property

        Public Property _From() As String
            Get
                Return atrFrom
            End Get
            Set(ByVal value As String)
                atrFrom = value
            End Set
        End Property

        Public Property Where() As String
            Get
                Return atrWhere
            End Get
            Set(ByVal value As String)
                atrWhere = value
            End Set
        End Property

        Public Property Group() As String
            Get
                Return atrGroup
            End Get
            Set(ByVal value As String)
                atrGroup = value
            End Set
        End Property

        Public Property Order() As String
            Get
                Return atrOrder
            End Get
            Set(ByVal value As String)
                atrOrder = value
            End Set
        End Property

        Public Property Having() As String
            Get
                Return atrHaving
            End Get
            Set(ByVal value As String)
                atrHaving = value
            End Set
        End Property

        Public Property FiltrosGlobal() As ClsFiltrosGlobal
            Get
                Return atrFiltrosGlobal
            End Get
            Set(ByVal value As ClsFiltrosGlobal)
                atrFiltrosGlobal = value
            End Set
        End Property


        Public Property CamposGlobal() As ClsCamposGlobal
            Get
                Return atrCamposGlobal
            End Get
            Set(ByVal value As ClsCamposGlobal)
                atrCamposGlobal = value
            End Set
        End Property

        Public Property Campos() As ClsCampos()
            Get
                Return atrCampos
            End Get
            Set(ByVal value As ClsCampos())
                atrCampos = value
            End Set
        End Property


        Public Property Query() As String
            Get
                Return atrQuery
            End Get
            Set(ByVal value As String)
                atrQuery = value
            End Set
        End Property


        Public Property Columnas() As ClsColumnas()
            Get
                Return atrColumnas
            End Get
            Set(ByVal value As ClsColumnas())
                atrColumnas = value
            End Set
        End Property

        Public Property Agrupacion() As ClsAgrupacion()
            Get
                Return atrAgrupacion
            End Get
            Set(ByVal value As ClsAgrupacion())
                atrAgrupacion = value
            End Set
        End Property


        Public Property Ordenacion() As ClsOrdenacion()
            Get
                Return atrOrdenacion
            End Get
            Set(ByVal value As ClsOrdenacion())
                atrOrdenacion = value
            End Set
        End Property

        Public Property PiesPagina() As String()
            Get
                Return atrPiesPagina
            End Get
            Set(ByVal value As String())
                atrPiesPagina = value
            End Set
        End Property


        Public Property Encabezados() As String()
            Get
                Return atrEncabezados
            End Get
            Set(ByVal value As String())
                atrEncabezados = value
            End Set
        End Property


        Public Property Filtros() As ClsFiltros()
            Get
                Return atrFiltros
            End Get
            Set(ByVal value As ClsFiltros())
                atrFiltros = value
            End Set
        End Property

        Public Property Totales() As ClsTotales()
            Get
                Return atrTotales
            End Get
            Set(ByVal value As ClsTotales())
                atrTotales = value
            End Set
        End Property


        Public Property ModificaColumnas() As Boolean
            Get
                Return atrModificaColumnas
            End Get
            Set(ByVal value As Boolean)
                atrModificaColumnas = value
            End Set
        End Property

        Public Property ModificaAgrupacion() As Boolean
            Get
                Return atrModificaAgrupacion
            End Get
            Set(ByVal value As Boolean)
                atrModificaAgrupacion = value
            End Set
        End Property

        Public Property ModificaOrdenacion() As Boolean
            Get
                Return atrModificaOrdenacion
            End Get
            Set(ByVal value As Boolean)
                atrModificaOrdenacion = value
            End Set
        End Property

        Public Property ModificaTotales() As Boolean
            Get
                Return atrModificaTotales
            End Get
            Set(ByVal value As Boolean)
                atrModificaTotales = value
            End Set
        End Property

        Public Property OmitirAlias() As Boolean
            Get
                Return atrOmitirAlias
            End Get
            Set(ByVal value As Boolean)
                atrOmitirAlias = value
            End Set
        End Property

        Public Sub New(ByVal prmfolio As Integer)
            MyBase.New(prmfolio)
            atrCamposGlobal = New ClsCamposGlobal(Me)
            atrFiltrosGlobal = New ClsFiltrosGlobal(Me)
            Dim DAO As DataAccessCls = DataAccessCls.DevuelveInstancia
            DAO.RegresaConsultaSQL("select * from ADSUM_ReporteExpressColumnas where nreporte=" & Folio, dtFormatos)
        End Sub


        Public Overrides Function FormatoFolio() As String
            Return ""
        End Function

        Public Overrides Function getNombreFolioAdministrado() As String
            DAO.FolioAdministradoAgregar("Adsum_Reportes", "Reportes Adsum")
            Return "Adsum_Reportes"
        End Function

        Public Overrides Function getRow() As ClsBaseComun.ObtenerRowEventHandler
            Return AddressOf FabricaReportes.ObtenReportes
        End Function

        Public Overrides Function Guardar() As Boolean
            Return EscribanoReportes.Guardar(Me)
        End Function


        Public Function GetSchema() As System.Xml.Schema.XmlSchema Implements System.Xml.Serialization.IXmlSerializable.GetSchema

        End Function

        Public Sub ReadXml(ByVal reader As System.Xml.XmlReader) Implements System.Xml.Serialization.IXmlSerializable.ReadXml

        End Sub

        Public Sub WriteXml(ByVal writer As System.Xml.XmlWriter) Implements System.Xml.Serialization.IXmlSerializable.WriteXml

        End Sub
    End Class ' Reportes
End Namespace