using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Runtime.InteropServices;
using System.IO;
using System.Reflection;
using System.Windows.Resources;

namespace UserControlsSIZ.Iconos
{
    /// <summary>
    /// Interaction logic for IconSIZ.xaml
    /// </summary>
    public partial class IconAwesomeSIZ : UserControl
    {
        #region FontAwesome old


        //        public enum AwesomeIcons
        //        {
        //            fa_500px = 0,
        //            fa_adjust = 1,
        //            fa_adn = 2,
        //            fa_align_center = 3,
        //            fa_align_justify = 4,
        //            fa_align_left = 5,
        //            fa_align_right = 6,
        //            fa_amazon = 7,
        //            fa_ambulance = 8,
        //            fa_american_sign_language_interpreting = 9,
        //            fa_anchor = 10,
        //            fa_android = 11,
        //            fa_angellist = 12,
        //            fa_angle_double_down = 13,
        //            fa_angle_double_left = 14,
        //            fa_angle_double_right = 15,
        //            fa_angle_double_up = 16,
        //            fa_angle_down = 17,
        //            fa_angle_left = 18,
        //            fa_angle_right = 19,
        //            fa_angle_up = 20,
        //            fa_apple = 21,
        //            fa_archive = 22,
        //            fa_area_chart = 23,
        //            fa_arrow_circle_down = 24,
        //            fa_arrow_circle_left = 25,
        //            fa_arrow_circle_o_down = 26,
        //            fa_arrow_circle_o_left = 27,
        //            fa_arrow_circle_o_right = 28,
        //            fa_arrow_circle_o_up = 29,
        //            fa_arrow_circle_right = 30,
        //            fa_arrow_circle_up = 31,
        //            fa_arrow_down = 32,
        //            fa_arrow_left = 33,
        //            fa_arrow_right = 34,
        //            fa_arrow_up = 35,
        //            fa_arrows = 36,
        //            fa_arrows_alt = 37,
        //            fa_arrows_h = 38,
        //            fa_arrows_v = 39,
        //            fa_asl_interpreting = 40,
        //            fa_assistive_listening_systems = 41,
        //            fa_asterisk = 42,
        //            fa_at = 43,
        //            fa_audio_description = 44,
        //            fa_automobile = 45,
        //            fa_backward = 46,
        //            fa_balance_scale = 47,
        //            fa_ban = 48,
        //            fa_bank = 49,
        //            fa_bar_chart = 50,
        //            fa_bar_chart_o = 51,
        //            fa_barcode = 52,
        //            fa_bars = 53,
        //            fa_battery_0 = 54,
        //            fa_battery_1 = 55,
        //            fa_battery_2 = 56,
        //            fa_battery_3 = 57,
        //            fa_battery_4 = 58,
        //            fa_battery_empty = 59,
        //            fa_battery_full = 60,
        //            fa_battery_half = 61,
        //            fa_battery_quarter = 62,
        //            fa_battery_three_quarters = 63,
        //            fa_bed = 64,
        //            fa_beer = 65,
        //            fa_behance = 66,
        //            fa_behance_square = 67,
        //            fa_bell = 68,
        //            fa_bell_o = 69,
        //            fa_bell_slash = 70,
        //            fa_bell_slash_o = 71,
        //            fa_bicycle = 72,
        //            fa_binoculars = 73,
        //            fa_birthday_cake = 74,
        //            fa_bitbucket = 75,
        //            fa_bitbucket_square = 76,
        //            fa_bitcoin = 77,
        //            fa_black_tie = 78,
        //            fa_blind = 79,
        //            fa_bluetooth = 80,
        //            fa_bluetooth_b = 81,
        //            fa_bold = 82,
        //            fa_bolt = 83,
        //            fa_bomb = 84,
        //            fa_book = 85,
        //            fa_bookmark = 86,
        //            fa_bookmark_o = 87,
        //            fa_braille = 88,
        //            fa_briefcase = 89,
        //            fa_btc = 90,
        //            fa_bug = 91,
        //            fa_building = 92,
        //            fa_building_o = 93,
        //            fa_bullhorn = 94,
        //            fa_bullseye = 95,
        //            fa_bus = 96,
        //            fa_buysellads = 97,
        //            fa_cab = 98,
        //            fa_calculator = 99,
        //            fa_calendar = 100,
        //            fa_calendar_check_o = 101,
        //            fa_calendar_minus_o = 102,
        //            fa_calendar_o = 103,
        //            fa_calendar_plus_o = 104,
        //            fa_calendar_times_o = 105,
        //            fa_camera = 106,
        //            fa_camera_retro = 107,
        //            fa_car = 108,
        //            fa_caret_down = 109,
        //            fa_caret_left = 110,
        //            fa_caret_right = 111,
        //            fa_caret_square_o_down = 112,
        //            fa_caret_square_o_left = 113,
        //            fa_caret_square_o_right = 114,
        //            fa_caret_square_o_up = 115,
        //            fa_caret_up = 116,
        //            fa_cart_arrow_down = 117,
        //            fa_cart_plus = 118,
        //            fa_cc = 119,
        //            fa_cc_amex = 120,
        //            fa_cc_diners_club = 121,
        //            fa_cc_discover = 122,
        //            fa_cc_jcb = 123,
        //            fa_cc_mastercard = 124,
        //            fa_cc_paypal = 125,
        //            fa_cc_stripe = 126,
        //            fa_cc_visa = 127,
        //            fa_certificate = 128,
        //            fa_chain = 129,
        //            fa_chain_broken = 130,
        //            fa_check = 131,
        //            fa_check_circle = 132,
        //            fa_check_circle_o = 133,
        //            fa_check_square = 134,
        //            fa_check_square_o = 135,
        //            fa_chevron_circle_down = 136,
        //            fa_chevron_circle_left = 137,
        //            fa_chevron_circle_right = 138,
        //            fa_chevron_circle_up = 139,
        //            fa_chevron_down = 140,
        //            fa_chevron_left = 141,
        //            fa_chevron_right = 142,
        //            fa_chevron_up = 143,
        //            fa_child = 144,
        //            fa_chrome = 145,
        //            fa_circle = 146,
        //            fa_circle_o = 147,
        //            fa_circle_o_notch = 148,
        //            fa_circle_thin = 149,
        //            fa_clipboard = 150,
        //            fa_clock_o = 151,
        //            fa_clone = 152,
        //            fa_close = 153,
        //            fa_cloud = 154,
        //            fa_cloud_download = 155,
        //            fa_cloud_upload = 156,
        //            fa_cny = 157,
        //            fa_code = 158,
        //            fa_code_fork = 159,
        //            fa_codepen = 160,
        //            fa_codiepie = 161,
        //            fa_coffee = 162,
        //            fa_cog = 163,
        //            fa_cogs = 164,
        //            fa_columns = 165,
        //            fa_comment = 166,
        //            fa_comment_o = 167,
        //            fa_commenting = 168,
        //            fa_commenting_o = 169,
        //            fa_comments = 170,
        //            fa_comments_o = 171,
        //            fa_compass = 172,
        //            fa_compress = 173,
        //            fa_connectdevelop = 174,
        //            fa_contao = 175,
        //            fa_copy = 176,
        //            fa_copyright = 177,
        //            fa_creative_commons = 178,
        //            fa_credit_card = 179,
        //            fa_credit_card_alt = 180,
        //            fa_crop = 181,
        //            fa_crosshairs = 182,
        //            fa_css3 = 183,
        //            fa_cube = 184,
        //            fa_cubes = 185,
        //            fa_cut = 186,
        //            fa_cutlery = 187,
        //            fa_dashboard = 188,
        //            fa_dashcube = 189,
        //            fa_database = 190,
        //            fa_deaf = 191,
        //            fa_deafness = 192,
        //            fa_dedent = 193,
        //            fa_delicious = 194,
        //            fa_desktop = 195,
        //            fa_deviantart = 196,
        //            fa_diamond = 197,
        //            fa_digg = 198,
        //            fa_dollar = 199,
        //            fa_dot_circle_o = 200,
        //            fa_download = 201,
        //            fa_dribbble = 202,
        //            fa_dropbox = 203,
        //            fa_drupal = 204,
        //            fa_edge = 205,
        //            fa_edit = 206,
        //            fa_eject = 207,
        //            fa_ellipsis_h = 208,
        //            fa_ellipsis_v = 209,
        //            fa_empire = 210,
        //            fa_envelope = 211,
        //            fa_envelope_o = 212,
        //            fa_envelope_square = 213,
        //            fa_envira = 214,
        //            fa_eraser = 215,
        //            fa_eur = 216,
        //            fa_euro = 217,
        //            fa_exchange = 218,
        //            fa_exclamation = 219,
        //            fa_exclamation_circle = 220,
        //            fa_exclamation_triangle = 221,
        //            fa_expand = 222,
        //            fa_expeditedssl = 223,
        //            fa_external_link = 224,
        //            fa_external_link_square = 225,
        //            fa_eye = 226,
        //            fa_eye_slash = 227,
        //            fa_eyedropper = 228,
        //            fa_fa = 229,
        //            fa_facebook = 230,
        //            fa_facebook_f = 231,
        //            fa_facebook_official = 232,
        //            fa_facebook_square = 233,
        //            fa_fast_backward = 234,
        //            fa_fast_forward = 235,
        //            fa_fax = 236,
        //            fa_feed = 237,
        //            fa_female = 238,
        //            fa_fighter_jet = 239,
        //            fa_file = 240,
        //            fa_file_archive_o = 241,
        //            fa_file_audio_o = 242,
        //            fa_file_code_o = 243,
        //            fa_file_excel_o = 244,
        //            fa_file_image_o = 245,
        //            fa_file_movie_o = 246,
        //            fa_file_o = 247,
        //            fa_file_pdf_o = 248,
        //            fa_file_photo_o = 249,
        //            fa_file_picture_o = 250,
        //            fa_file_powerpoint_o = 251,
        //            fa_file_sound_o = 252,
        //            fa_file_text = 253,
        //            fa_file_text_o = 254,
        //            fa_file_video_o = 255,
        //            fa_file_word_o = 256,
        //            fa_file_zip_o = 257,
        //            fa_files_o = 258,
        //            fa_film = 259,
        //            fa_filter = 260,
        //            fa_fire = 261,
        //            fa_fire_extinguisher = 262,
        //            fa_firefox = 263,
        //            fa_first_order = 264,
        //            fa_flag = 265,
        //            fa_flag_checkered = 266,
        //            fa_flag_o = 267,
        //            fa_flash = 268,
        //            fa_flask = 269,
        //            fa_flickr = 270,
        //            fa_floppy_o = 271,
        //            fa_folder = 272,
        //            fa_folder_o = 273,
        //            fa_folder_open = 274,
        //            fa_folder_open_o = 275,
        //            fa_font = 276,
        //            fa_font_awesome = 277,
        //            fa_fonticons = 278,
        //            fa_fort_awesome = 279,
        //            fa_forumbee = 280,
        //            fa_forward = 281,
        //            fa_foursquare = 282,
        //            fa_frown_o = 283,
        //            fa_futbol_o = 284,
        //            fa_gamepad = 285,
        //            fa_gavel = 286,
        //            fa_gbp = 287,
        //            fa_ge = 288,
        //            fa_gear = 289,
        //            fa_gears = 290,
        //            fa_genderless = 291,
        //            fa_get_pocket = 292,
        //            fa_gg = 293,
        //            fa_gg_circle = 294,
        //            fa_gift = 295,
        //            fa_git = 296,
        //            fa_git_square = 297,
        //            fa_github = 298,
        //            fa_github_alt = 299,
        //            fa_github_square = 300,
        //            fa_gitlab = 301,
        //            fa_gittip = 302,
        //            fa_glass = 303,
        //            fa_glide = 304,
        //            fa_glide_g = 305,
        //            fa_globe = 306,
        //            fa_google = 307,
        //            fa_google_plus = 308,
        //            fa_google_plus_circle = 309,
        //            fa_google_plus_official = 310,
        //            fa_google_plus_square = 311,
        //            fa_google_wallet = 312,
        //            fa_graduation_cap = 313,
        //            fa_gratipay = 314,
        //            fa_group = 315,
        //            fa_h_square = 316,
        //            fa_hacker_news = 317,
        //            fa_hand_grab_o = 318,
        //            fa_hand_lizard_o = 319,
        //            fa_hand_o_down = 320,
        //            fa_hand_o_left = 321,
        //            fa_hand_o_right = 322,
        //            fa_hand_o_up = 323,
        //            fa_hand_paper_o = 324,
        //            fa_hand_peace_o = 325,
        //            fa_hand_pointer_o = 326,
        //            fa_hand_rock_o = 327,
        //            fa_hand_scissors_o = 328,
        //            fa_hand_spock_o = 329,
        //            fa_hand_stop_o = 330,
        //            fa_hard_of_hearing = 331,
        //            fa_hashtag = 332,
        //            fa_hdd_o = 333,
        //            fa_header = 334,
        //            fa_headphones = 335,
        //            fa_heart = 336,
        //            fa_heart_o = 337,
        //            fa_heartbeat = 338,
        //            fa_history = 339,
        //            fa_home = 340,
        //            fa_hospital_o = 341,
        //            fa_hotel = 342,
        //            fa_hourglass = 343,
        //            fa_hourglass_1 = 344,
        //            fa_hourglass_2 = 345,
        //            fa_hourglass_3 = 346,
        //            fa_hourglass_end = 347,
        //            fa_hourglass_half = 348,
        //            fa_hourglass_o = 349,
        //            fa_hourglass_start = 350,
        //            fa_houzz = 351,
        //            fa_html5 = 352,
        //            fa_i_cursor = 353,
        //            fa_ils = 354,
        //            fa_image = 355,
        //            fa_inbox = 356,
        //            fa_indent = 357,
        //            fa_industry = 358,
        //            fa_info = 359,
        //            fa_info_circle = 360,
        //            fa_inr = 361,
        //            fa_instagram = 362,
        //            fa_institution = 363,
        //            fa_internet_explorer = 364,
        //            fa_intersex = 365,
        //            fa_ioxhost = 366,
        //            fa_italic = 367,
        //            fa_joomla = 368,
        //            fa_jpy = 369,
        //            fa_jsfiddle = 370,
        //            fa_key = 371,
        //            fa_keyboard_o = 372,
        //            fa_krw = 373,
        //            fa_language = 374,
        //            fa_laptop = 375,
        //            fa_lastfm = 376,
        //            fa_lastfm_square = 377,
        //            fa_leaf = 378,
        //            fa_leanpub = 379,
        //            fa_legal = 380,
        //            fa_lemon_o = 381,
        //            fa_level_down = 382,
        //            fa_level_up = 383,
        //            fa_life_bouy = 384,
        //            fa_life_buoy = 385,
        //            fa_life_ring = 386,
        //            fa_life_saver = 387,
        //            fa_lightbulb_o = 388,
        //            fa_line_chart = 389,
        //            fa_link = 390,
        //            fa_linkedin = 391,
        //            fa_linkedin_square = 392,
        //            fa_linux = 393,
        //            fa_list = 394,
        //            fa_list_alt = 395,
        //            fa_list_ol = 396,
        //            fa_list_ul = 397,
        //            fa_location_arrow = 398,
        //            fa_lock = 399,
        //            fa_long_arrow_down = 400,
        //            fa_long_arrow_left = 401,
        //            fa_long_arrow_right = 402,
        //            fa_long_arrow_up = 403,
        //            fa_low_vision = 404,
        //            fa_magic = 405,
        //            fa_magnet = 406,
        //            fa_mail_forward = 407,
        //            fa_mail_reply = 408,
        //            fa_mail_reply_all = 409,
        //            fa_male = 410,
        //            fa_map = 411,
        //            fa_map_marker = 412,
        //            fa_map_o = 413,
        //            fa_map_pin = 414,
        //            fa_map_signs = 415,
        //            fa_mars = 416,
        //            fa_mars_double = 417,
        //            fa_mars_stroke = 418,
        //            fa_mars_stroke_h = 419,
        //            fa_mars_stroke_v = 420,
        //            fa_maxcdn = 421,
        //            fa_meanpath = 422,
        //            fa_medium = 423,
        //            fa_medkit = 424,
        //            fa_meh_o = 425,
        //            fa_mercury = 426,
        //            fa_microphone = 427,
        //            fa_microphone_slash = 428,
        //            fa_minus = 429,
        //            fa_minus_circle = 430,
        //            fa_minus_square = 431,
        //            fa_minus_square_o = 432,
        //            fa_mixcloud = 433,
        //            fa_mobile = 434,
        //            fa_mobile_phone = 435,
        //            fa_modx = 436,
        //            fa_money = 437,
        //            fa_moon_o = 438,
        //            fa_mortar_board = 439,
        //            fa_motorcycle = 440,
        //            fa_mouse_pointer = 441,
        //            fa_music = 442,
        //            fa_navicon = 443,
        //            fa_neuter = 444,
        //            fa_newspaper_o = 445,
        //            fa_object_group = 446,
        //            fa_object_ungroup = 447,
        //            fa_odnoklassniki = 448,
        //            fa_odnoklassniki_square = 449,
        //            fa_opencart = 450,
        //            fa_openid = 451,
        //            fa_opera = 452,
        //            fa_optin_monster = 453,
        //            fa_outdent = 454,
        //            fa_pagelines = 455,
        //            fa_paint_brush = 456,
        //            fa_paper_plane = 457,
        //            fa_paper_plane_o = 458,
        //            fa_paperclip = 459,
        //            fa_paragraph = 460,
        //            fa_paste = 461,
        //            fa_pause = 462,
        //            fa_pause_circle = 463,
        //            fa_pause_circle_o = 464,
        //            fa_paw = 465,
        //            fa_paypal = 466,
        //            fa_pencil = 467,
        //            fa_pencil_square = 468,
        //            fa_pencil_square_o = 469,
        //            fa_percent = 470,
        //            fa_phone = 471,
        //            fa_phone_square = 472,
        //            fa_photo = 473,
        //            fa_picture_o = 474,
        //            fa_pie_chart = 475,
        //            fa_pied_piper = 476,
        //            fa_pied_piper_alt = 477,
        //            fa_pied_piper_pp = 478,
        //            fa_pinterest = 479,
        //            fa_pinterest_p = 480,
        //            fa_pinterest_square = 481,
        //            fa_plane = 482,
        //            fa_play = 483,
        //            fa_play_circle = 484,
        //            fa_play_circle_o = 485,
        //            fa_plug = 486,
        //            fa_plus = 487,
        //            fa_plus_circle = 488,
        //            fa_plus_square = 489,
        //            fa_plus_square_o = 490,
        //            fa_power_off = 491,
        //            fa_print = 492,
        //            fa_product_hunt = 493,
        //            fa_puzzle_piece = 494,
        //            fa_qq = 495,
        //            fa_qrcode = 496,
        //            fa_question = 497,
        //            fa_question_circle = 498,
        //            fa_question_circle_o = 499,
        //            fa_quote_left = 500,
        //            fa_quote_right = 501,
        //            fa_ra = 502,
        //            fa_random = 503,
        //            fa_rebel = 504,
        //            fa_recycle = 505,
        //            fa_reddit = 506,
        //            fa_reddit_alien = 507,
        //            fa_reddit_square = 508,
        //            fa_refresh = 509,
        //            fa_registered = 510,
        //            fa_remove = 511,
        //            fa_renren = 512,
        //            fa_reorder = 513,
        //            fa_repeat = 514,
        //            fa_reply = 515,
        //            fa_reply_all = 516,
        //            fa_resistance = 517,
        //            fa_retweet = 518,
        //            fa_rmb = 519,
        //            fa_road = 520,
        //            fa_rocket = 521,
        //            fa_rotate_left = 522,
        //            fa_rotate_right = 523,
        //            fa_rouble = 524,
        //            fa_rss = 525,
        //            fa_rss_square = 526,
        //            fa_rub = 527,
        //            fa_ruble = 528,
        //            fa_rupee = 529,
        //            fa_safari = 530,
        //            fa_save = 531,
        //            fa_scissors = 532,
        //            fa_scribd = 533,
        //            fa_search = 534,
        //            fa_search_minus = 535,
        //            fa_search_plus = 536,
        //            fa_sellsy = 537,
        //            fa_send = 538,
        //            fa_send_o = 539,
        //            fa_server = 540,
        //            fa_share = 541,
        //            fa_share_alt = 542,
        //            fa_share_alt_square = 543,
        //            fa_share_square = 544,
        //            fa_share_square_o = 545,
        //            fa_shekel = 546,
        //            fa_sheqel = 547,
        //            fa_shield = 548,
        //            fa_ship = 549,
        //            fa_shirtsinbulk = 550,
        //            fa_shopping_bag = 551,
        //            fa_shopping_basket = 552,
        //            fa_shopping_cart = 553,
        //            fa_sign_in = 554,
        //            fa_sign_language = 555,
        //            fa_sign_out = 556,
        //            fa_signal = 557,
        //            fa_signing = 558,
        //            fa_simplybuilt = 559,
        //            fa_sitemap = 560,
        //            fa_skyatlas = 561,
        //            fa_skype = 562,
        //            fa_slack = 563,
        //            fa_sliders = 564,
        //            fa_slideshare = 565,
        //            fa_smile_o = 566,
        //            fa_snapchat = 567,
        //            fa_snapchat_ghost = 568,
        //            fa_snapchat_square = 569,
        //            fa_soccer_ball_o = 570,
        //            fa_sort = 571,
        //            fa_sort_alpha_asc = 572,
        //            fa_sort_alpha_desc = 573,
        //            fa_sort_amount_asc = 574,
        //            fa_sort_amount_desc = 575,
        //            fa_sort_asc = 576,
        //            fa_sort_desc = 577,
        //            fa_sort_down = 578,
        //            fa_sort_numeric_asc = 579,
        //            fa_sort_numeric_desc = 580,
        //            fa_sort_up = 581,
        //            fa_soundcloud = 582,
        //            fa_space_shuttle = 583,
        //            fa_spinner = 584,
        //            fa_spoon = 585,
        //            fa_spotify = 586,
        //            fa_square = 587,
        //            fa_square_o = 588,
        //            fa_stack_exchange = 589,
        //            fa_stack_overflow = 590,
        //            fa_star = 591,
        //            fa_star_half = 592,
        //            fa_star_half_empty = 593,
        //            fa_star_half_full = 594,
        //            fa_star_half_o = 595,
        //            fa_star_o = 596,
        //            fa_steam = 597,
        //            fa_steam_square = 598,
        //            fa_step_backward = 599,
        //            fa_step_forward = 600,
        //            fa_stethoscope = 601,
        //            fa_sticky_note = 602,
        //            fa_sticky_note_o = 603,
        //            fa_stop = 604,
        //            fa_stop_circle = 605,
        //            fa_stop_circle_o = 606,
        //            fa_street_view = 607,
        //            fa_strikethrough = 608,
        //            fa_stumbleupon = 609,
        //            fa_stumbleupon_circle = 610,
        //            fa_subscript = 611,
        //            fa_subway = 612,
        //            fa_suitcase = 613,
        //            fa_sun_o = 614,
        //            fa_superscript = 615,
        //            fa_support = 616,
        //            fa_table = 617,
        //            fa_tablet = 618,
        //            fa_tachometer = 619,
        //            fa_tag = 620,
        //            fa_tags = 621,
        //            fa_tasks = 622,
        //            fa_taxi = 623,
        //            fa_television = 624,
        //            fa_tencent_weibo = 625,
        //            fa_terminal = 626,
        //            fa_text_height = 627,
        //            fa_text_width = 628,
        //            fa_th = 629,
        //            fa_th_large = 630,
        //            fa_th_list = 631,
        //            fa_themeisle = 632,
        //            fa_thumb_tack = 633,
        //            fa_thumbs_down = 634,
        //            fa_thumbs_o_down = 635,
        //            fa_thumbs_o_up = 636,
        //            fa_thumbs_up = 637,
        //            fa_ticket = 638,
        //            fa_times = 639,
        //            fa_times_circle = 640,
        //            fa_times_circle_o = 641,
        //            fa_tint = 642,
        //            fa_toggle_down = 643,
        //            fa_toggle_left = 644,
        //            fa_toggle_off = 645,
        //            fa_toggle_on = 646,
        //            fa_toggle_right = 647,
        //            fa_toggle_up = 648,
        //            fa_trademark = 649,
        //            fa_train = 650,
        //            fa_transgender = 651,
        //            fa_transgender_alt = 652,
        //            fa_trash = 653,
        //            fa_trash_o = 654,
        //            fa_tree = 655,
        //            fa_trello = 656,
        //            fa_tripadvisor = 657,
        //            fa_trophy = 658,
        //            fa_truck = 659,
        //            fa_try = 660,
        //            fa_tty = 661,
        //            fa_tumblr = 662,
        //            fa_tumblr_square = 663,
        //            fa_turkish_lira = 664,
        //            fa_tv = 665,
        //            fa_twitch = 666,
        //            fa_twitter = 667,
        //            fa_twitter_square = 668,
        //            fa_umbrella = 669,
        //            fa_underline = 670,
        //            fa_undo = 671,
        //            fa_universal_access = 672,
        //            fa_university = 673,
        //            fa_unlink = 674,
        //            fa_unlock = 675,
        //            fa_unlock_alt = 676,
        //            fa_unsorted = 677,
        //            fa_upload = 678,
        //            fa_usb = 679,
        //            fa_usd = 680,
        //            fa_user = 681,
        //            fa_user_md = 682,
        //            fa_user_plus = 683,
        //            fa_user_secret = 684,
        //            fa_user_times = 685,
        //            fa_users = 686,
        //            fa_venus = 687,
        //            fa_venus_double = 688,
        //            fa_venus_mars = 689,
        //            fa_viacoin = 690,
        //            fa_viadeo = 691,
        //            fa_viadeo_square = 692,
        //            fa_video_camera = 693,
        //            fa_vimeo = 694,
        //            fa_vimeo_square = 695,
        //            fa_vine = 696,
        //            fa_vk = 697,
        //            fa_volume_control_phone = 698,
        //            fa_volume_down = 699,
        //            fa_volume_off = 700,
        //            fa_volume_up = 701,
        //            fa_warning = 702,
        //            fa_wechat = 703,
        //            fa_weibo = 704,
        //            fa_weixin = 705,
        //            fa_whatsapp = 706,
        //            fa_wheelchair = 707,
        //            fa_wheelchair_alt = 708,
        //            fa_wifi = 709,
        //            fa_wikipedia_w = 710,
        //            fa_windows = 711,
        //            fa_won = 712,
        //            fa_wordpress = 713,
        //            fa_wpbeginner = 714,
        //            fa_wpforms = 715,
        //            fa_wrench = 716,
        //            fa_xing = 717,
        //            fa_xing_square = 718,
        //            fa_y_combinator = 719,
        //            fa_y_combinator_square = 720,
        //            fa_yahoo = 721,
        //            fa_yc = 722,
        //            fa_yc_square = 723,
        //            fa_yelp = 724,
        //            fa_yen = 725,
        //            fa_yoast = 726,
        //            fa_youtube = 727,
        //            fa_youtube_play = 728,
        //            fa_youtube_square = 729
        //        }

        //        static String[] codigos = {
        //"\uf26e",
        //"\uf042",
        //"\uf170",
        //"\uf037",
        //"\uf039",
        //"\uf036",
        //"\uf038",
        //"\uf270",
        //"\uf0f9",
        //"\uf2a3",
        //"\uf13d",
        //"\uf17b",
        //"\uf209",
        //"\uf103",
        //"\uf100",
        //"\uf101",
        //"\uf102",
        //"\uf107",
        //"\uf104",
        //"\uf105",
        //"\uf106",
        //"\uf179",
        //"\uf187",
        //"\uf1fe",
        //"\uf0ab",
        //"\uf0a8",
        //"\uf01a",
        //"\uf190",
        //"\uf18e",
        //"\uf01b",
        //"\uf0a9",
        //"\uf0aa",
        //"\uf063",
        //"\uf060",
        //"\uf061",
        //"\uf062",
        //"\uf047",
        //"\uf0b2",
        //"\uf07e",
        //"\uf07d",
        //"\uf2a3",
        //"\uf2a2",
        //"\uf069",
        //"\uf1fa",
        //"\uf29e",
        //"\uf1b9",
        //"\uf04a",
        //"\uf24e",
        //"\uf05e",
        //"\uf19c",
        //"\uf080",
        //"\uf080",
        //"\uf02a",
        //"\uf0c9",
        //"\uf244",
        //"\uf243",
        //"\uf242",
        //"\uf241",
        //"\uf240",
        //"\uf244",
        //"\uf240",
        //"\uf242",
        //"\uf243",
        //"\uf241",
        //"\uf236",
        //"\uf0fc",
        //"\uf1b4",
        //"\uf1b5",
        //"\uf0f3",
        //"\uf0a2",
        //"\uf1f6",
        //"\uf1f7",
        //"\uf206",
        //"\uf1e5",
        //"\uf1fd",
        //"\uf171",
        //"\uf172",
        //"\uf15a",
        //"\uf27e",
        //"\uf29d",
        //"\uf293",
        //"\uf294",
        //"\uf032",
        //"\uf0e7",
        //"\uf1e2",
        //"\uf02d",
        //"\uf02e",
        //"\uf097",
        //"\uf2a1",
        //"\uf0b1",
        //"\uf15a",
        //"\uf188",
        //"\uf1ad",
        //"\uf0f7",
        //"\uf0a1",
        //"\uf140",
        //"\uf207",
        //"\uf20d",
        //"\uf1ba",
        //"\uf1ec",
        //"\uf073",
        //"\uf274",
        //"\uf272",
        //"\uf133",
        //"\uf271",
        //"\uf273",
        //"\uf030",
        //"\uf083",
        //"\uf1b9",
        //"\uf0d7",
        //"\uf0d9",
        //"\uf0da",
        //"\uf150",
        //"\uf191",
        //"\uf152",
        //"\uf151",
        //"\uf0d8",
        //"\uf218",
        //"\uf217",
        //"\uf20a",
        //"\uf1f3",
        //"\uf24c",
        //"\uf1f2",
        //"\uf24b",
        //"\uf1f1",
        //"\uf1f4",
        //"\uf1f5",
        //"\uf1f0",
        //"\uf0a3",
        //"\uf0c1",
        //"\uf127",
        //"\uf00c",
        //"\uf058",
        //"\uf05d",
        //"\uf14a",
        //"\uf046",
        //"\uf13a",
        //"\uf137",
        //"\uf138",
        //"\uf139",
        //"\uf078",
        //"\uf053",
        //"\uf054",
        //"\uf077",
        //"\uf1ae",
        //"\uf268",
        //"\uf111",
        //"\uf10c",
        //"\uf1ce",
        //"\uf1db",
        //"\uf0ea",
        //"\uf017",
        //"\uf24d",
        //"\uf00d",
        //"\uf0c2",
        //"\uf0ed",
        //"\uf0ee",
        //"\uf157",
        //"\uf121",
        //"\uf126",
        //"\uf1cb",
        //"\uf284",
        //"\uf0f4",
        //"\uf013",
        //"\uf085",
        //"\uf0db",
        //"\uf075",
        //"\uf0e5",
        //"\uf27a",
        //"\uf27b",
        //"\uf086",
        //"\uf0e6",
        //"\uf14e",
        //"\uf066",
        //"\uf20e",
        //"\uf26d",
        //"\uf0c5",
        //"\uf1f9",
        //"\uf25e",
        //"\uf09d",
        //"\uf283",
        //"\uf125",
        //"\uf05b",
        //"\uf13c",
        //"\uf1b2",
        //"\uf1b3",
        //"\uf0c4",
        //"\uf0f5",
        //"\uf0e4",
        //"\uf210",
        //"\uf1c0",
        //"\uf2a4",
        //"\uf2a4",
        //"\uf03b",
        //"\uf1a5",
        //"\uf108",
        //"\uf1bd",
        //"\uf219",
        //"\uf1a6",
        //"\uf155",
        //"\uf192",
        //"\uf019",
        //"\uf17d",
        //"\uf16b",
        //"\uf1a9",
        //"\uf282",
        //"\uf044",
        //"\uf052",
        //"\uf141",
        //"\uf142",
        //"\uf1d1",
        //"\uf0e0",
        //"\uf003",
        //"\uf199",
        //"\uf299",
        //"\uf12d",
        //"\uf153",
        //"\uf153",
        //"\uf0ec",
        //"\uf12a",
        //"\uf06a",
        //"\uf071",
        //"\uf065",
        //"\uf23e",
        //"\uf08e",
        //"\uf14c",
        //"\uf06e",
        //"\uf070",
        //"\uf1fb",
        //"\uf2b4",
        //"\uf09a",
        //"\uf09a",
        //"\uf230",
        //"\uf082",
        //"\uf049",
        //"\uf050",
        //"\uf1ac",
        //"\uf09e",
        //"\uf182",
        //"\uf0fb",
        //"\uf15b",
        //"\uf1c6",
        //"\uf1c7",
        //"\uf1c9",
        //"\uf1c3",
        //"\uf1c5",
        //"\uf1c8",
        //"\uf016",
        //"\uf1c1",
        //"\uf1c5",
        //"\uf1c5",
        //"\uf1c4",
        //"\uf1c7",
        //"\uf15c",
        //"\uf0f6",
        //"\uf1c8",
        //"\uf1c2",
        //"\uf1c6",
        //"\uf0c5",
        //"\uf008",
        //"\uf0b0",
        //"\uf06d",
        //"\uf134",
        //"\uf269",
        //"\uf2b0",
        //"\uf024",
        //"\uf11e",
        //"\uf11d",
        //"\uf0e7",
        //"\uf0c3",
        //"\uf16e",
        //"\uf0c7",
        //"\uf07b",
        //"\uf114",
        //"\uf07c",
        //"\uf115",
        //"\uf031",
        //"\uf2b4",
        //"\uf280",
        //"\uf286",
        //"\uf211",
        //"\uf04e",
        //"\uf180",
        //"\uf119",
        //"\uf1e3",
        //"\uf11b",
        //"\uf0e3",
        //"\uf154",
        //"\uf1d1",
        //"\uf013",
        //"\uf085",
        //"\uf22d",
        //"\uf265",
        //"\uf260",
        //"\uf261",
        //"\uf06b",
        //"\uf1d3",
        //"\uf1d2",
        //"\uf09b",
        //"\uf113",
        //"\uf092",
        //"\uf296",
        //"\uf184",
        //"\uf000",
        //"\uf2a5",
        //"\uf2a6",
        //"\uf0ac",
        //"\uf1a0",
        //"\uf0d5",
        //"\uf2b3",
        //"\uf2b3",
        //"\uf0d4",
        //"\uf1ee",
        //"\uf19d",
        //"\uf184",
        //"\uf0c0",
        //"\uf0fd",
        //"\uf1d4",
        //"\uf255",
        //"\uf258",
        //"\uf0a7",
        //"\uf0a5",
        //"\uf0a4",
        //"\uf0a6",
        //"\uf256",
        //"\uf25b",
        //"\uf25a",
        //"\uf255",
        //"\uf257",
        //"\uf259",
        //"\uf256",
        //"\uf2a4",
        //"\uf292",
        //"\uf0a0",
        //"\uf1dc",
        //"\uf025",
        //"\uf004",
        //"\uf08a",
        //"\uf21e",
        //"\uf1da",
        //"\uf015",
        //"\uf0f8",
        //"\uf236",
        //"\uf254",
        //"\uf251",
        //"\uf252",
        //"\uf253",
        //"\uf253",
        //"\uf252",
        //"\uf250",
        //"\uf251",
        //"\uf27c",
        //"\uf13b",
        //"\uf246",
        //"\uf20b",
        //"\uf03e",
        //"\uf01c",
        //"\uf03c",
        //"\uf275",
        //"\uf129",
        //"\uf05a",
        //"\uf156",
        //"\uf16d",
        //"\uf19c",
        //"\uf26b",
        //"\uf224",
        //"\uf208",
        //"\uf033",
        //"\uf1aa",
        //"\uf157",
        //"\uf1cc",
        //"\uf084",
        //"\uf11c",
        //"\uf159",
        //"\uf1ab",
        //"\uf109",
        //"\uf202",
        //"\uf203",
        //"\uf06c",
        //"\uf212",
        //"\uf0e3",
        //"\uf094",
        //"\uf149",
        //"\uf148",
        //"\uf1cd",
        //"\uf1cd",
        //"\uf1cd",
        //"\uf1cd",
        //"\uf0eb",
        //"\uf201",
        //"\uf0c1",
        //"\uf0e1",
        //"\uf08c",
        //"\uf17c",
        //"\uf03a",
        //"\uf022",
        //"\uf0cb",
        //"\uf0ca",
        //"\uf124",
        //"\uf023",
        //"\uf175",
        //"\uf177",
        //"\uf178",
        //"\uf176",
        //"\uf2a8",
        //"\uf0d0",
        //"\uf076",
        //"\uf064",
        //"\uf112",
        //"\uf122",
        //"\uf183",
        //"\uf279",
        //"\uf041",
        //"\uf278",
        //"\uf276",
        //"\uf277",
        //"\uf222",
        //"\uf227",
        //"\uf229",
        //"\uf22b",
        //"\uf22a",
        //"\uf136",
        //"\uf20c",
        //"\uf23a",
        //"\uf0fa",
        //"\uf11a",
        //"\uf223",
        //"\uf130",
        //"\uf131",
        //"\uf068",
        //"\uf056",
        //"\uf146",
        //"\uf147",
        //"\uf289",
        //"\uf10b",
        //"\uf10b",
        //"\uf285",
        //"\uf0d6",
        //"\uf186",
        //"\uf19d",
        //"\uf21c",
        //"\uf245",
        //"\uf001",
        //"\uf0c9",
        //"\uf22c",
        //"\uf1ea",
        //"\uf247",
        //"\uf248",
        //"\uf263",
        //"\uf264",
        //"\uf23d",
        //"\uf19b",
        //"\uf26a",
        //"\uf23c",
        //"\uf03b",
        //"\uf18c",
        //"\uf1fc",
        //"\uf1d8",
        //"\uf1d9",
        //"\uf0c6",
        //"\uf1dd",
        //"\uf0ea",
        //"\uf04c",
        //"\uf28b",
        //"\uf28c",
        //"\uf1b0",
        //"\uf1ed",
        //"\uf040",
        //"\uf14b",
        //"\uf044",
        //"\uf295",
        //"\uf095",
        //"\uf098",
        //"\uf03e",
        //"\uf03e",
        //"\uf200",
        //"\uf2ae",
        //"\uf1a8",
        //"\uf1a7",
        //"\uf0d2",
        //"\uf231",
        //"\uf0d3",
        //"\uf072",
        //"\uf04b",
        //"\uf144",
        //"\uf01d",
        //"\uf1e6",
        //"\uf067",
        //"\uf055",
        //"\uf0fe",
        //"\uf196",
        //"\uf011",
        //"\uf02f",
        //"\uf288",
        //"\uf12e",
        //"\uf1d6",
        //"\uf029",
        //"\uf128",
        //"\uf059",
        //"\uf29c",
        //"\uf10d",
        //"\uf10e",
        //"\uf1d0",
        //"\uf074",
        //"\uf1d0",
        //"\uf1b8",
        //"\uf1a1",
        //"\uf281",
        //"\uf1a2",
        //"\uf021",
        //"\uf25d",
        //"\uf00d",
        //"\uf18b",
        //"\uf0c9",
        //"\uf01e",
        //"\uf112",
        //"\uf122",
        //"\uf1d0",
        //"\uf079",
        //"\uf157",
        //"\uf018",
        //"\uf135",
        //"\uf0e2",
        //"\uf01e",
        //"\uf158",
        //"\uf09e",
        //"\uf143",
        //"\uf158",
        //"\uf158",
        //"\uf156",
        //"\uf267",
        //"\uf0c7",
        //"\uf0c4",
        //"\uf28a",
        //"\uf002",
        //"\uf010",
        //"\uf00e",
        //"\uf213",
        //"\uf1d8",
        //"\uf1d9",
        //"\uf233",
        //"\uf064",
        //"\uf1e0",
        //"\uf1e1",
        //"\uf14d",
        //"\uf045",
        //"\uf20b",
        //"\uf20b",
        //"\uf132",
        //"\uf21a",
        //"\uf214",
        //"\uf290",
        //"\uf291",
        //"\uf07a",
        //"\uf090",
        //"\uf2a7",
        //"\uf08b",
        //"\uf012",
        //"\uf2a7",
        //"\uf215",
        //"\uf0e8",
        //"\uf216",
        //"\uf17e",
        //"\uf198",
        //"\uf1de",
        //"\uf1e7",
        //"\uf118",
        //"\uf2ab",
        //"\uf2ac",
        //"\uf2ad",
        //"\uf1e3",
        //"\uf0dc",
        //"\uf15d",
        //"\uf15e",
        //"\uf160",
        //"\uf161",
        //"\uf0de",
        //"\uf0dd",
        //"\uf0dd",
        //"\uf162",
        //"\uf163",
        //"\uf0de",
        //"\uf1be",
        //"\uf197",
        //"\uf110",
        //"\uf1b1",
        //"\uf1bc",
        //"\uf0c8",
        //"\uf096",
        //"\uf18d",
        //"\uf16c",
        //"\uf005",
        //"\uf089",
        //"\uf123",
        //"\uf123",
        //"\uf123",
        //"\uf006",
        //"\uf1b6",
        //"\uf1b7",
        //"\uf048",
        //"\uf051",
        //"\uf0f1",
        //"\uf249",
        //"\uf24a",
        //"\uf04d",
        //"\uf28d",
        //"\uf28e",
        //"\uf21d",
        //"\uf0cc",
        //"\uf1a4",
        //"\uf1a3",
        //"\uf12c",
        //"\uf239",
        //"\uf0f2",
        //"\uf185",
        //"\uf12b",
        //"\uf1cd",
        //"\uf0ce",
        //"\uf10a",
        //"\uf0e4",
        //"\uf02b",
        //"\uf02c",
        //"\uf0ae",
        //"\uf1ba",
        //"\uf26c",
        //"\uf1d5",
        //"\uf120",
        //"\uf034",
        //"\uf035",
        //"\uf00a",
        //"\uf009",
        //"\uf00b",
        //"\uf2b2",
        //"\uf08d",
        //"\uf165",
        //"\uf088",
        //"\uf087",
        //"\uf164",
        //"\uf145",
        //"\uf00d",
        //"\uf057",
        //"\uf05c",
        //"\uf043",
        //"\uf150",
        //"\uf191",
        //"\uf204",
        //"\uf205",
        //"\uf152",
        //"\uf151",
        //"\uf25c",
        //"\uf238",
        //"\uf224",
        //"\uf225",
        //"\uf1f8",
        //"\uf014",
        //"\uf1bb",
        //"\uf181",
        //"\uf262",
        //"\uf091",
        //"\uf0d1",
        //"\uf195",
        //"\uf1e4",
        //"\uf173",
        //"\uf174",
        //"\uf195",
        //"\uf26c",
        //"\uf1e8",
        //"\uf099",
        //"\uf081",
        //"\uf0e9",
        //"\uf0cd",
        //"\uf0e2",
        //"\uf29a",
        //"\uf19c",
        //"\uf127",
        //"\uf09c",
        //"\uf13e",
        //"\uf0dc",
        //"\uf093",
        //"\uf287",
        //"\uf155",
        //"\uf007",
        //"\uf0f0",
        //"\uf234",
        //"\uf21b",
        //"\uf235",
        //"\uf0c0",
        //"\uf221",
        //"\uf226",
        //"\uf228",
        //"\uf237",
        //"\uf2a9",
        //"\uf2aa",
        //"\uf03d",
        //"\uf27d",
        //"\uf194",
        //"\uf1ca",
        //"\uf189",
        //"\uf2a0",
        //"\uf027",
        //"\uf026",
        //"\uf028",
        //"\uf071",
        //"\uf1d7",
        //"\uf18a",
        //"\uf1d7",
        //"\uf232",
        //"\uf193",
        //"\uf29b",
        //"\uf1eb",
        //"\uf266",
        //"\uf17a",
        //"\uf159",
        //"\uf19a",
        //"\uf297",
        //"\uf298",
        //"\uf0ad",
        //"\uf168",
        //"\uf169",
        //"\uf23b",
        //"\uf1d4",
        //"\uf19e",
        //"\uf23b",
        //"\uf1d4",
        //"\uf1e9",
        //"\uf157",
        //"\uf2b1",
        //"\uf167",
        //"\uf16a",
        //"\uf166"
        //};
        #endregion

        #region FontAwesome 4.7.0
        public enum AwesomeIcons
        {
            fa_500px = 0,
            fa_address_book = 1,
            fa_address_book_o = 2,
            fa_address_card = 3,
            fa_address_card_o = 4,
            fa_adjust = 5,
            fa_adn = 6,
            fa_align_center = 7,
            fa_align_justify = 8,
            fa_align_left = 9,
            fa_align_right = 10,
            fa_amazon = 11,
            fa_ambulance = 12,
            fa_american_sign_language_interpreting = 13,
            fa_anchor = 14,
            fa_android = 15,
            fa_angellist = 16,
            fa_angle_double_down = 17,
            fa_angle_double_left = 18,
            fa_angle_double_right = 19,
            fa_angle_double_up = 20,
            fa_angle_down = 21,
            fa_angle_left = 22,
            fa_angle_right = 23,
            fa_angle_up = 24,
            fa_apple = 25,
            fa_archive = 26,
            fa_area_chart = 27,
            fa_arrow_circle_down = 28,
            fa_arrow_circle_left = 29,
            fa_arrow_circle_o_down = 30,
            fa_arrow_circle_o_left = 31,
            fa_arrow_circle_o_right = 32,
            fa_arrow_circle_o_up = 33,
            fa_arrow_circle_right = 34,
            fa_arrow_circle_up = 35,
            fa_arrow_down = 36,
            fa_arrow_left = 37,
            fa_arrow_right = 38,
            fa_arrow_up = 39,
            fa_arrows = 40,
            fa_arrows_alt = 41,
            fa_arrows_h = 42,
            fa_arrows_v = 43,
            fa_asl_interpreting = 44,
            fa_assistive_listening_systems = 45,
            fa_asterisk = 46,
            fa_at = 47,
            fa_audio_description = 48,
            fa_automobile = 49,
            fa_backward = 50,
            fa_balance_scale = 51,
            fa_ban = 52,
            fa_bandcamp = 53,
            fa_bank = 54,
            fa_bar_chart = 55,
            fa_bar_chart_o = 56,
            fa_barcode = 57,
            fa_bars = 58,
            fa_bath = 59,
            fa_bathtub = 60,
            fa_battery = 61,
            fa_battery_0 = 62,
            fa_battery_1 = 63,
            fa_battery_2 = 64,
            fa_battery_3 = 65,
            fa_battery_4 = 66,
            fa_battery_empty = 67,
            fa_battery_full = 68,
            fa_battery_half = 69,
            fa_battery_quarter = 70,
            fa_battery_three_quarters = 71,
            fa_bed = 72,
            fa_beer = 73,
            fa_behance = 74,
            fa_behance_square = 75,
            fa_bell = 76,
            fa_bell_o = 77,
            fa_bell_slash = 78,
            fa_bell_slash_o = 79,
            fa_bicycle = 80,
            fa_binoculars = 81,
            fa_birthday_cake = 82,
            fa_bitbucket = 83,
            fa_bitbucket_square = 84,
            fa_bitcoin = 85,
            fa_black_tie = 86,
            fa_blind = 87,
            fa_bluetooth = 88,
            fa_bluetooth_b = 89,
            fa_bold = 90,
            fa_bolt = 91,
            fa_bomb = 92,
            fa_book = 93,
            fa_bookmark = 94,
            fa_bookmark_o = 95,
            fa_braille = 96,
            fa_briefcase = 97,
            fa_btc = 98,
            fa_bug = 99,
            fa_building = 100,
            fa_building_o = 101,
            fa_bullhorn = 102,
            fa_bullseye = 103,
            fa_bus = 104,
            fa_buysellads = 105,
            fa_cab = 106,
            fa_calculator = 107,
            fa_calendar = 108,
            fa_calendar_check_o = 109,
            fa_calendar_minus_o = 110,
            fa_calendar_o = 111,
            fa_calendar_plus_o = 112,
            fa_calendar_times_o = 113,
            fa_camera = 114,
            fa_camera_retro = 115,
            fa_car = 116,
            fa_caret_down = 117,
            fa_caret_left = 118,
            fa_caret_right = 119,
            fa_caret_square_o_down = 120,
            fa_caret_square_o_left = 121,
            fa_caret_square_o_right = 122,
            fa_caret_square_o_up = 123,
            fa_caret_up = 124,
            fa_cart_arrow_down = 125,
            fa_cart_plus = 126,
            fa_cc = 127,
            fa_cc_amex = 128,
            fa_cc_diners_club = 129,
            fa_cc_discover = 130,
            fa_cc_jcb = 131,
            fa_cc_mastercard = 132,
            fa_cc_paypal = 133,
            fa_cc_stripe = 134,
            fa_cc_visa = 135,
            fa_certificate = 136,
            fa_chain = 137,
            fa_chain_broken = 138,
            fa_check = 139,
            fa_check_circle = 140,
            fa_check_circle_o = 141,
            fa_check_square = 142,
            fa_check_square_o = 143,
            fa_chevron_circle_down = 144,
            fa_chevron_circle_left = 145,
            fa_chevron_circle_right = 146,
            fa_chevron_circle_up = 147,
            fa_chevron_down = 148,
            fa_chevron_left = 149,
            fa_chevron_right = 150,
            fa_chevron_up = 151,
            fa_child = 152,
            fa_chrome = 153,
            fa_circle = 154,
            fa_circle_o = 155,
            fa_circle_o_notch = 156,
            fa_circle_thin = 157,
            fa_clipboard = 158,
            fa_clock_o = 159,
            fa_clone = 160,
            fa_close = 161,
            fa_cloud = 162,
            fa_cloud_download = 163,
            fa_cloud_upload = 164,
            fa_cny = 165,
            fa_code = 166,
            fa_code_fork = 167,
            fa_codepen = 168,
            fa_codiepie = 169,
            fa_coffee = 170,
            fa_cog = 171,
            fa_cogs = 172,
            fa_columns = 173,
            fa_comment = 174,
            fa_comment_o = 175,
            fa_commenting = 176,
            fa_commenting_o = 177,
            fa_comments = 178,
            fa_comments_o = 179,
            fa_compass = 180,
            fa_compress = 181,
            fa_connectdevelop = 182,
            fa_contao = 183,
            fa_copy = 184,
            fa_copyright = 185,
            fa_creative_commons = 186,
            fa_credit_card = 187,
            fa_credit_card_alt = 188,
            fa_crop = 189,
            fa_crosshairs = 190,
            fa_css3 = 191,
            fa_cube = 192,
            fa_cubes = 193,
            fa_cut = 194,
            fa_cutlery = 195,
            fa_dashboard = 196,
            fa_dashcube = 197,
            fa_database = 198,
            fa_deaf = 199,
            fa_deafness = 200,
            fa_dedent = 201,
            fa_delicious = 202,
            fa_desktop = 203,
            fa_deviantart = 204,
            fa_diamond = 205,
            fa_digg = 206,
            fa_dollar = 207,
            fa_dot_circle_o = 208,
            fa_download = 209,
            fa_dribbble = 210,
            fa_drivers_license = 211,
            fa_drivers_license_o = 212,
            fa_dropbox = 213,
            fa_drupal = 214,
            fa_edge = 215,
            fa_edit = 216,
            fa_eercast = 217,
            fa_eject = 218,
            fa_ellipsis_h = 219,
            fa_ellipsis_v = 220,
            fa_empire = 221,
            fa_envelope = 222,
            fa_envelope_o = 223,
            fa_envelope_open = 224,
            fa_envelope_open_o = 225,
            fa_envelope_square = 226,
            fa_envira = 227,
            fa_eraser = 228,
            fa_etsy = 229,
            fa_eur = 230,
            fa_euro = 231,
            fa_exchange = 232,
            fa_exclamation = 233,
            fa_exclamation_circle = 234,
            fa_exclamation_triangle = 235,
            fa_expand = 236,
            fa_expeditedssl = 237,
            fa_external_link = 238,
            fa_external_link_square = 239,
            fa_eye = 240,
            fa_eye_slash = 241,
            fa_eyedropper = 242,
            fa_fa = 243,
            fa_facebook = 244,
            fa_facebook_f = 245,
            fa_facebook_official = 246,
            fa_facebook_square = 247,
            fa_fast_backward = 248,
            fa_fast_forward = 249,
            fa_fax = 250,
            fa_feed = 251,
            fa_female = 252,
            fa_fighter_jet = 253,
            fa_file = 254,
            fa_file_archive_o = 255,
            fa_file_audio_o = 256,
            fa_file_code_o = 257,
            fa_file_excel_o = 258,
            fa_file_image_o = 259,
            fa_file_movie_o = 260,
            fa_file_o = 261,
            fa_file_pdf_o = 262,
            fa_file_photo_o = 263,
            fa_file_picture_o = 264,
            fa_file_powerpoint_o = 265,
            fa_file_sound_o = 266,
            fa_file_text = 267,
            fa_file_text_o = 268,
            fa_file_video_o = 269,
            fa_file_word_o = 270,
            fa_file_zip_o = 271,
            fa_files_o = 272,
            fa_film = 273,
            fa_filter = 274,
            fa_fire = 275,
            fa_fire_extinguisher = 276,
            fa_firefox = 277,
            fa_first_order = 278,
            fa_flag = 279,
            fa_flag_checkered = 280,
            fa_flag_o = 281,
            fa_flash = 282,
            fa_flask = 283,
            fa_flickr = 284,
            fa_floppy_o = 285,
            fa_folder = 286,
            fa_folder_o = 287,
            fa_folder_open = 288,
            fa_folder_open_o = 289,
            fa_font = 290,
            fa_font_awesome = 291,
            fa_fonticons = 292,
            fa_fort_awesome = 293,
            fa_forumbee = 294,
            fa_forward = 295,
            fa_foursquare = 296,
            fa_free_code_camp = 297,
            fa_frown_o = 298,
            fa_futbol_o = 299,
            fa_gamepad = 300,
            fa_gavel = 301,
            fa_gbp = 302,
            fa_ge = 303,
            fa_gear = 304,
            fa_gears = 305,
            fa_genderless = 306,
            fa_get_pocket = 307,
            fa_gg = 308,
            fa_gg_circle = 309,
            fa_gift = 310,
            fa_git = 311,
            fa_git_square = 312,
            fa_github = 313,
            fa_github_alt = 314,
            fa_github_square = 315,
            fa_gitlab = 316,
            fa_gittip = 317,
            fa_glass = 318,
            fa_glide = 319,
            fa_glide_g = 320,
            fa_globe = 321,
            fa_google = 322,
            fa_google_plus = 323,
            fa_google_plus_circle = 324,
            fa_google_plus_official = 325,
            fa_google_plus_square = 326,
            fa_google_wallet = 327,
            fa_graduation_cap = 328,
            fa_gratipay = 329,
            fa_grav = 330,
            fa_group = 331,
            fa_h_square = 332,
            fa_hacker_news = 333,
            fa_hand_grab_o = 334,
            fa_hand_lizard_o = 335,
            fa_hand_o_down = 336,
            fa_hand_o_left = 337,
            fa_hand_o_right = 338,
            fa_hand_o_up = 339,
            fa_hand_paper_o = 340,
            fa_hand_peace_o = 341,
            fa_hand_pointer_o = 342,
            fa_hand_rock_o = 343,
            fa_hand_scissors_o = 344,
            fa_hand_spock_o = 345,
            fa_hand_stop_o = 346,
            fa_handshake_o = 347,
            fa_hard_of_hearing = 348,
            fa_hashtag = 349,
            fa_hdd_o = 350,
            fa_header = 351,
            fa_headphones = 352,
            fa_heart = 353,
            fa_heart_o = 354,
            fa_heartbeat = 355,
            fa_history = 356,
            fa_home = 357,
            fa_hospital_o = 358,
            fa_hotel = 359,
            fa_hourglass = 360,
            fa_hourglass_1 = 361,
            fa_hourglass_2 = 362,
            fa_hourglass_3 = 363,
            fa_hourglass_end = 364,
            fa_hourglass_half = 365,
            fa_hourglass_o = 366,
            fa_hourglass_start = 367,
            fa_houzz = 368,
            fa_html5 = 369,
            fa_i_cursor = 370,
            fa_id_badge = 371,
            fa_id_card = 372,
            fa_id_card_o = 373,
            fa_ils = 374,
            fa_image = 375,
            fa_imdb = 376,
            fa_inbox = 377,
            fa_indent = 378,
            fa_industry = 379,
            fa_info = 380,
            fa_info_circle = 381,
            fa_inr = 382,
            fa_instagram = 383,
            fa_institution = 384,
            fa_internet_explorer = 385,
            fa_intersex = 386,
            fa_ioxhost = 387,
            fa_italic = 388,
            fa_joomla = 389,
            fa_jpy = 390,
            fa_jsfiddle = 391,
            fa_key = 392,
            fa_keyboard_o = 393,
            fa_krw = 394,
            fa_language = 395,
            fa_laptop = 396,
            fa_lastfm = 397,
            fa_lastfm_square = 398,
            fa_leaf = 399,
            fa_leanpub = 400,
            fa_legal = 401,
            fa_lemon_o = 402,
            fa_level_down = 403,
            fa_level_up = 404,
            fa_life_bouy = 405,
            fa_life_buoy = 406,
            fa_life_ring = 407,
            fa_life_saver = 408,
            fa_lightbulb_o = 409,
            fa_line_chart = 410,
            fa_link = 411,
            fa_linkedin = 412,
            fa_linkedin_square = 413,
            fa_linode = 414,
            fa_linux = 415,
            fa_list = 416,
            fa_list_alt = 417,
            fa_list_ol = 418,
            fa_list_ul = 419,
            fa_location_arrow = 420,
            fa_lock = 421,
            fa_long_arrow_down = 422,
            fa_long_arrow_left = 423,
            fa_long_arrow_right = 424,
            fa_long_arrow_up = 425,
            fa_low_vision = 426,
            fa_magic = 427,
            fa_magnet = 428,
            fa_mail_forward = 429,
            fa_mail_reply = 430,
            fa_mail_reply_all = 431,
            fa_male = 432,
            fa_map = 433,
            fa_map_marker = 434,
            fa_map_o = 435,
            fa_map_pin = 436,
            fa_map_signs = 437,
            fa_mars = 438,
            fa_mars_double = 439,
            fa_mars_stroke = 440,
            fa_mars_stroke_h = 441,
            fa_mars_stroke_v = 442,
            fa_maxcdn = 443,
            fa_meanpath = 444,
            fa_medium = 445,
            fa_medkit = 446,
            fa_meetup = 447,
            fa_meh_o = 448,
            fa_mercury = 449,
            fa_microchip = 450,
            fa_microphone = 451,
            fa_microphone_slash = 452,
            fa_minus = 453,
            fa_minus_circle = 454,
            fa_minus_square = 455,
            fa_minus_square_o = 456,
            fa_mixcloud = 457,
            fa_mobile = 458,
            fa_mobile_phone = 459,
            fa_modx = 460,
            fa_money = 461,
            fa_moon_o = 462,
            fa_mortar_board = 463,
            fa_motorcycle = 464,
            fa_mouse_pointer = 465,
            fa_music = 466,
            fa_navicon = 467,
            fa_neuter = 468,
            fa_newspaper_o = 469,
            fa_object_group = 470,
            fa_object_ungroup = 471,
            fa_odnoklassniki = 472,
            fa_odnoklassniki_square = 473,
            fa_opencart = 474,
            fa_openid = 475,
            fa_opera = 476,
            fa_optin_monster = 477,
            fa_outdent = 478,
            fa_pagelines = 479,
            fa_paint_brush = 480,
            fa_paper_plane = 481,
            fa_paper_plane_o = 482,
            fa_paperclip = 483,
            fa_paragraph = 484,
            fa_paste = 485,
            fa_pause = 486,
            fa_pause_circle = 487,
            fa_pause_circle_o = 488,
            fa_paw = 489,
            fa_paypal = 490,
            fa_pencil = 491,
            fa_pencil_square = 492,
            fa_pencil_square_o = 493,
            fa_percent = 494,
            fa_phone = 495,
            fa_phone_square = 496,
            fa_photo = 497,
            fa_picture_o = 498,
            fa_pie_chart = 499,
            fa_pied_piper = 500,
            fa_pied_piper_alt = 501,
            fa_pied_piper_pp = 502,
            fa_pinterest = 503,
            fa_pinterest_p = 504,
            fa_pinterest_square = 505,
            fa_plane = 506,
            fa_play = 507,
            fa_play_circle = 508,
            fa_play_circle_o = 509,
            fa_plug = 510,
            fa_plus = 511,
            fa_plus_circle = 512,
            fa_plus_square = 513,
            fa_plus_square_o = 514,
            fa_podcast = 515,
            fa_power_off = 516,
            fa_print = 517,
            fa_product_hunt = 518,
            fa_puzzle_piece = 519,
            fa_qq = 520,
            fa_qrcode = 521,
            fa_question = 522,
            fa_question_circle = 523,
            fa_question_circle_o = 524,
            fa_quora = 525,
            fa_quote_left = 526,
            fa_quote_right = 527,
            fa_ra = 528,
            fa_random = 529,
            fa_ravelry = 530,
            fa_rebel = 531,
            fa_recycle = 532,
            fa_reddit = 533,
            fa_reddit_alien = 534,
            fa_reddit_square = 535,
            fa_refresh = 536,
            fa_registered = 537,
            fa_remove = 538,
            fa_renren = 539,
            fa_reorder = 540,
            fa_repeat = 541,
            fa_reply = 542,
            fa_reply_all = 543,
            fa_resistance = 544,
            fa_retweet = 545,
            fa_rmb = 546,
            fa_road = 547,
            fa_rocket = 548,
            fa_rotate_left = 549,
            fa_rotate_right = 550,
            fa_rouble = 551,
            fa_rss = 552,
            fa_rss_square = 553,
            fa_rub = 554,
            fa_ruble = 555,
            fa_rupee = 556,
            fa_s15 = 557,
            fa_safari = 558,
            fa_save = 559,
            fa_scissors = 560,
            fa_scribd = 561,
            fa_search = 562,
            fa_search_minus = 563,
            fa_search_plus = 564,
            fa_sellsy = 565,
            fa_send = 566,
            fa_send_o = 567,
            fa_server = 568,
            fa_share = 569,
            fa_share_alt = 570,
            fa_share_alt_square = 571,
            fa_share_square = 572,
            fa_share_square_o = 573,
            fa_shekel = 574,
            fa_sheqel = 575,
            fa_shield = 576,
            fa_ship = 577,
            fa_shirtsinbulk = 578,
            fa_shopping_bag = 579,
            fa_shopping_basket = 580,
            fa_shopping_cart = 581,
            fa_shower = 582,
            fa_sign_in = 583,
            fa_sign_language = 584,
            fa_sign_out = 585,
            fa_signal = 586,
            fa_signing = 587,
            fa_simplybuilt = 588,
            fa_sitemap = 589,
            fa_skyatlas = 590,
            fa_skype = 591,
            fa_slack = 592,
            fa_sliders = 593,
            fa_slideshare = 594,
            fa_smile_o = 595,
            fa_snapchat = 596,
            fa_snapchat_ghost = 597,
            fa_snapchat_square = 598,
            fa_snowflake_o = 599,
            fa_soccer_ball_o = 600,
            fa_sort = 601,
            fa_sort_alpha_asc = 602,
            fa_sort_alpha_desc = 603,
            fa_sort_amount_asc = 604,
            fa_sort_amount_desc = 605,
            fa_sort_asc = 606,
            fa_sort_desc = 607,
            fa_sort_down = 608,
            fa_sort_numeric_asc = 609,
            fa_sort_numeric_desc = 610,
            fa_sort_up = 611,
            fa_soundcloud = 612,
            fa_space_shuttle = 613,
            fa_spinner = 614,
            fa_spoon = 615,
            fa_spotify = 616,
            fa_square = 617,
            fa_square_o = 618,
            fa_stack_exchange = 619,
            fa_stack_overflow = 620,
            fa_star = 621,
            fa_star_half = 622,
            fa_star_half_empty = 623,
            fa_star_half_full = 624,
            fa_star_half_o = 625,
            fa_star_o = 626,
            fa_steam = 627,
            fa_steam_square = 628,
            fa_step_backward = 629,
            fa_step_forward = 630,
            fa_stethoscope = 631,
            fa_sticky_note = 632,
            fa_sticky_note_o = 633,
            fa_stop = 634,
            fa_stop_circle = 635,
            fa_stop_circle_o = 636,
            fa_street_view = 637,
            fa_strikethrough = 638,
            fa_stumbleupon = 639,
            fa_stumbleupon_circle = 640,
            fa_subscript = 641,
            fa_subway = 642,
            fa_suitcase = 643,
            fa_sun_o = 644,
            fa_superpowers = 645,
            fa_superscript = 646,
            fa_support = 647,
            fa_table = 648,
            fa_tablet = 649,
            fa_tachometer = 650,
            fa_tag = 651,
            fa_tags = 652,
            fa_tasks = 653,
            fa_taxi = 654,
            fa_telegram = 655,
            fa_television = 656,
            fa_tencent_weibo = 657,
            fa_terminal = 658,
            fa_text_height = 659,
            fa_text_width = 660,
            fa_th = 661,
            fa_th_large = 662,
            fa_th_list = 663,
            fa_themeisle = 664,
            fa_thermometer = 665,
            fa_thermometer_0 = 666,
            fa_thermometer_1 = 667,
            fa_thermometer_2 = 668,
            fa_thermometer_3 = 669,
            fa_thermometer_4 = 670,
            fa_thermometer_empty = 671,
            fa_thermometer_full = 672,
            fa_thermometer_half = 673,
            fa_thermometer_quarter = 674,
            fa_thermometer_three_quarters = 675,
            fa_thumb_tack = 676,
            fa_thumbs_down = 677,
            fa_thumbs_o_down = 678,
            fa_thumbs_o_up = 679,
            fa_thumbs_up = 680,
            fa_ticket = 681,
            fa_times = 682,
            fa_times_circle = 683,
            fa_times_circle_o = 684,
            fa_times_rectangle = 685,
            fa_times_rectangle_o = 686,
            fa_tint = 687,
            fa_toggle_down = 688,
            fa_toggle_left = 689,
            fa_toggle_off = 690,
            fa_toggle_on = 691,
            fa_toggle_right = 692,
            fa_toggle_up = 693,
            fa_trademark = 694,
            fa_train = 695,
            fa_transgender = 696,
            fa_transgender_alt = 697,
            fa_trash = 698,
            fa_trash_o = 699,
            fa_tree = 700,
            fa_trello = 701,
            fa_tripadvisor = 702,
            fa_trophy = 703,
            fa_truck = 704,
            fa_try = 705,
            fa_tty = 706,
            fa_tumblr = 707,
            fa_tumblr_square = 708,
            fa_turkish_lira = 709,
            fa_tv = 710,
            fa_twitch = 711,
            fa_twitter = 712,
            fa_twitter_square = 713,
            fa_umbrella = 714,
            fa_underline = 715,
            fa_undo = 716,
            fa_universal_access = 717,
            fa_university = 718,
            fa_unlink = 719,
            fa_unlock = 720,
            fa_unlock_alt = 721,
            fa_unsorted = 722,
            fa_upload = 723,
            fa_usb = 724,
            fa_usd = 725,
            fa_user = 726,
            fa_user_circle = 727,
            fa_user_circle_o = 728,
            fa_user_md = 729,
            fa_user_o = 730,
            fa_user_plus = 731,
            fa_user_secret = 732,
            fa_user_times = 733,
            fa_users = 734,
            fa_vcard = 735,
            fa_vcard_o = 736,
            fa_venus = 737,
            fa_venus_double = 738,
            fa_venus_mars = 739,
            fa_viacoin = 740,
            fa_viadeo = 741,
            fa_viadeo_square = 742,
            fa_video_camera = 743,
            fa_vimeo = 744,
            fa_vimeo_square = 745,
            fa_vine = 746,
            fa_vk = 747,
            fa_volume_control_phone = 748,
            fa_volume_down = 749,
            fa_volume_off = 750,
            fa_volume_up = 751,
            fa_warning = 752,
            fa_wechat = 753,
            fa_weibo = 754,
            fa_weixin = 755,
            fa_whatsapp = 756,
            fa_wheelchair = 757,
            fa_wheelchair_alt = 758,
            fa_wifi = 759,
            fa_wikipedia_w = 760,
            fa_window_close = 761,
            fa_window_close_o = 762,
            fa_window_maximize = 763,
            fa_window_minimize = 764,
            fa_window_restore = 765,
            fa_windows = 766,
            fa_won = 767,
            fa_wordpress = 768,
            fa_wpbeginner = 769,
            fa_wpexplorer = 770,
            fa_wpforms = 771,
            fa_wrench = 772,
            fa_xing = 773,
            fa_xing_square = 774,
            fa_y_combinator = 775,
            fa_y_combinator_square = 776,
            fa_yahoo = 777,
            fa_yc = 778,
            fa_yc_square = 779,
            fa_yelp = 780,
            fa_yen = 781,
            fa_yoast = 782,
            fa_youtube = 783,
            fa_youtube_play = 784,
            fa_youtube_square = 785
        }

        String[] codigos = {
"\uf26e",
"\uf2b9",
"\uf2ba",
"\uf2bb",
"\uf2bc",
"\uf042",
"\uf170",
"\uf037",
"\uf039",
"\uf036",
"\uf038",
"\uf270",
"\uf0f9",
"\uf2a3",
"\uf13d",
"\uf17b",
"\uf209",
"\uf103",
"\uf100",
"\uf101",
"\uf102",
"\uf107",
"\uf104",
"\uf105",
"\uf106",
"\uf179",
"\uf187",
"\uf1fe",
"\uf0ab",
"\uf0a8",
"\uf01a",
"\uf190",
"\uf18e",
"\uf01b",
"\uf0a9",
"\uf0aa",
"\uf063",
"\uf060",
"\uf061",
"\uf062",
"\uf047",
"\uf0b2",
"\uf07e",
"\uf07d",
"\uf2a3",
"\uf2a2",
"\uf069",
"\uf1fa",
"\uf29e",
"\uf1b9",
"\uf04a",
"\uf24e",
"\uf05e",
"\uf2d5",
"\uf19c",
"\uf080",
"\uf080",
"\uf02a",
"\uf0c9",
"\uf2cd",
"\uf2cd",
"\uf240",
"\uf244",
"\uf243",
"\uf242",
"\uf241",
"\uf240",
"\uf244",
"\uf240",
"\uf242",
"\uf243",
"\uf241",
"\uf236",
"\uf0fc",
"\uf1b4",
"\uf1b5",
"\uf0f3",
"\uf0a2",
"\uf1f6",
"\uf1f7",
"\uf206",
"\uf1e5",
"\uf1fd",
"\uf171",
"\uf172",
"\uf15a",
"\uf27e",
"\uf29d",
"\uf293",
"\uf294",
"\uf032",
"\uf0e7",
"\uf1e2",
"\uf02d",
"\uf02e",
"\uf097",
"\uf2a1",
"\uf0b1",
"\uf15a",
"\uf188",
"\uf1ad",
"\uf0f7",
"\uf0a1",
"\uf140",
"\uf207",
"\uf20d",
"\uf1ba",
"\uf1ec",
"\uf073",
"\uf274",
"\uf272",
"\uf133",
"\uf271",
"\uf273",
"\uf030",
"\uf083",
"\uf1b9",
"\uf0d7",
"\uf0d9",
"\uf0da",
"\uf150",
"\uf191",
"\uf152",
"\uf151",
"\uf0d8",
"\uf218",
"\uf217",
"\uf20a",
"\uf1f3",
"\uf24c",
"\uf1f2",
"\uf24b",
"\uf1f1",
"\uf1f4",
"\uf1f5",
"\uf1f0",
"\uf0a3",
"\uf0c1",
"\uf127",
"\uf00c",
"\uf058",
"\uf05d",
"\uf14a",
"\uf046",
"\uf13a",
"\uf137",
"\uf138",
"\uf139",
"\uf078",
"\uf053",
"\uf054",
"\uf077",
"\uf1ae",
"\uf268",
"\uf111",
"\uf10c",
"\uf1ce",
"\uf1db",
"\uf0ea",
"\uf017",
"\uf24d",
"\uf00d",
"\uf0c2",
"\uf0ed",
"\uf0ee",
"\uf157",
"\uf121",
"\uf126",
"\uf1cb",
"\uf284",
"\uf0f4",
"\uf013",
"\uf085",
"\uf0db",
"\uf075",
"\uf0e5",
"\uf27a",
"\uf27b",
"\uf086",
"\uf0e6",
"\uf14e",
"\uf066",
"\uf20e",
"\uf26d",
"\uf0c5",
"\uf1f9",
"\uf25e",
"\uf09d",
"\uf283",
"\uf125",
"\uf05b",
"\uf13c",
"\uf1b2",
"\uf1b3",
"\uf0c4",
"\uf0f5",
"\uf0e4",
"\uf210",
"\uf1c0",
"\uf2a4",
"\uf2a4",
"\uf03b",
"\uf1a5",
"\uf108",
"\uf1bd",
"\uf219",
"\uf1a6",
"\uf155",
"\uf192",
"\uf019",
"\uf17d",
"\uf2c2",
"\uf2c3",
"\uf16b",
"\uf1a9",
"\uf282",
"\uf044",
"\uf2da",
"\uf052",
"\uf141",
"\uf142",
"\uf1d1",
"\uf0e0",
"\uf003",
"\uf2b6",
"\uf2b7",
"\uf199",
"\uf299",
"\uf12d",
"\uf2d7",
"\uf153",
"\uf153",
"\uf0ec",
"\uf12a",
"\uf06a",
"\uf071",
"\uf065",
"\uf23e",
"\uf08e",
"\uf14c",
"\uf06e",
"\uf070",
"\uf1fb",
"\uf2b4",
"\uf09a",
"\uf09a",
"\uf230",
"\uf082",
"\uf049",
"\uf050",
"\uf1ac",
"\uf09e",
"\uf182",
"\uf0fb",
"\uf15b",
"\uf1c6",
"\uf1c7",
"\uf1c9",
"\uf1c3",
"\uf1c5",
"\uf1c8",
"\uf016",
"\uf1c1",
"\uf1c5",
"\uf1c5",
"\uf1c4",
"\uf1c7",
"\uf15c",
"\uf0f6",
"\uf1c8",
"\uf1c2",
"\uf1c6",
"\uf0c5",
"\uf008",
"\uf0b0",
"\uf06d",
"\uf134",
"\uf269",
"\uf2b0",
"\uf024",
"\uf11e",
"\uf11d",
"\uf0e7",
"\uf0c3",
"\uf16e",
"\uf0c7",
"\uf07b",
"\uf114",
"\uf07c",
"\uf115",
"\uf031",
"\uf2b4",
"\uf280",
"\uf286",
"\uf211",
"\uf04e",
"\uf180",
"\uf2c5",
"\uf119",
"\uf1e3",
"\uf11b",
"\uf0e3",
"\uf154",
"\uf1d1",
"\uf013",
"\uf085",
"\uf22d",
"\uf265",
"\uf260",
"\uf261",
"\uf06b",
"\uf1d3",
"\uf1d2",
"\uf09b",
"\uf113",
"\uf092",
"\uf296",
"\uf184",
"\uf000",
"\uf2a5",
"\uf2a6",
"\uf0ac",
"\uf1a0",
"\uf0d5",
"\uf2b3",
"\uf2b3",
"\uf0d4",
"\uf1ee",
"\uf19d",
"\uf184",
"\uf2d6",
"\uf0c0",
"\uf0fd",
"\uf1d4",
"\uf255",
"\uf258",
"\uf0a7",
"\uf0a5",
"\uf0a4",
"\uf0a6",
"\uf256",
"\uf25b",
"\uf25a",
"\uf255",
"\uf257",
"\uf259",
"\uf256",
"\uf2b5",
"\uf2a4",
"\uf292",
"\uf0a0",
"\uf1dc",
"\uf025",
"\uf004",
"\uf08a",
"\uf21e",
"\uf1da",
"\uf015",
"\uf0f8",
"\uf236",
"\uf254",
"\uf251",
"\uf252",
"\uf253",
"\uf253",
"\uf252",
"\uf250",
"\uf251",
"\uf27c",
"\uf13b",
"\uf246",
"\uf2c1",
"\uf2c2",
"\uf2c3",
"\uf20b",
"\uf03e",
"\uf2d8",
"\uf01c",
"\uf03c",
"\uf275",
"\uf129",
"\uf05a",
"\uf156",
"\uf16d",
"\uf19c",
"\uf26b",
"\uf224",
"\uf208",
"\uf033",
"\uf1aa",
"\uf157",
"\uf1cc",
"\uf084",
"\uf11c",
"\uf159",
"\uf1ab",
"\uf109",
"\uf202",
"\uf203",
"\uf06c",
"\uf212",
"\uf0e3",
"\uf094",
"\uf149",
"\uf148",
"\uf1cd",
"\uf1cd",
"\uf1cd",
"\uf1cd",
"\uf0eb",
"\uf201",
"\uf0c1",
"\uf0e1",
"\uf08c",
"\uf2b8",
"\uf17c",
"\uf03a",
"\uf022",
"\uf0cb",
"\uf0ca",
"\uf124",
"\uf023",
"\uf175",
"\uf177",
"\uf178",
"\uf176",
"\uf2a8",
"\uf0d0",
"\uf076",
"\uf064",
"\uf112",
"\uf122",
"\uf183",
"\uf279",
"\uf041",
"\uf278",
"\uf276",
"\uf277",
"\uf222",
"\uf227",
"\uf229",
"\uf22b",
"\uf22a",
"\uf136",
"\uf20c",
"\uf23a",
"\uf0fa",
"\uf2e0",
"\uf11a",
"\uf223",
"\uf2db",
"\uf130",
"\uf131",
"\uf068",
"\uf056",
"\uf146",
"\uf147",
"\uf289",
"\uf10b",
"\uf10b",
"\uf285",
"\uf0d6",
"\uf186",
"\uf19d",
"\uf21c",
"\uf245",
"\uf001",
"\uf0c9",
"\uf22c",
"\uf1ea",
"\uf247",
"\uf248",
"\uf263",
"\uf264",
"\uf23d",
"\uf19b",
"\uf26a",
"\uf23c",
"\uf03b",
"\uf18c",
"\uf1fc",
"\uf1d8",
"\uf1d9",
"\uf0c6",
"\uf1dd",
"\uf0ea",
"\uf04c",
"\uf28b",
"\uf28c",
"\uf1b0",
"\uf1ed",
"\uf040",
"\uf14b",
"\uf044",
"\uf295",
"\uf095",
"\uf098",
"\uf03e",
"\uf03e",
"\uf200",
"\uf2ae",
"\uf1a8",
"\uf1a7",
"\uf0d2",
"\uf231",
"\uf0d3",
"\uf072",
"\uf04b",
"\uf144",
"\uf01d",
"\uf1e6",
"\uf067",
"\uf055",
"\uf0fe",
"\uf196",
"\uf2ce",
"\uf011",
"\uf02f",
"\uf288",
"\uf12e",
"\uf1d6",
"\uf029",
"\uf128",
"\uf059",
"\uf29c",
"\uf2c4",
"\uf10d",
"\uf10e",
"\uf1d0",
"\uf074",
"\uf2d9",
"\uf1d0",
"\uf1b8",
"\uf1a1",
"\uf281",
"\uf1a2",
"\uf021",
"\uf25d",
"\uf00d",
"\uf18b",
"\uf0c9",
"\uf01e",
"\uf112",
"\uf122",
"\uf1d0",
"\uf079",
"\uf157",
"\uf018",
"\uf135",
"\uf0e2",
"\uf01e",
"\uf158",
"\uf09e",
"\uf143",
"\uf158",
"\uf158",
"\uf156",
"\uf2cd",
"\uf267",
"\uf0c7",
"\uf0c4",
"\uf28a",
"\uf002",
"\uf010",
"\uf00e",
"\uf213",
"\uf1d8",
"\uf1d9",
"\uf233",
"\uf064",
"\uf1e0",
"\uf1e1",
"\uf14d",
"\uf045",
"\uf20b",
"\uf20b",
"\uf132",
"\uf21a",
"\uf214",
"\uf290",
"\uf291",
"\uf07a",
"\uf2cc",
"\uf090",
"\uf2a7",
"\uf08b",
"\uf012",
"\uf2a7",
"\uf215",
"\uf0e8",
"\uf216",
"\uf17e",
"\uf198",
"\uf1de",
"\uf1e7",
"\uf118",
"\uf2ab",
"\uf2ac",
"\uf2ad",
"\uf2dc",
"\uf1e3",
"\uf0dc",
"\uf15d",
"\uf15e",
"\uf160",
"\uf161",
"\uf0de",
"\uf0dd",
"\uf0dd",
"\uf162",
"\uf163",
"\uf0de",
"\uf1be",
"\uf197",
"\uf110",
"\uf1b1",
"\uf1bc",
"\uf0c8",
"\uf096",
"\uf18d",
"\uf16c",
"\uf005",
"\uf089",
"\uf123",
"\uf123",
"\uf123",
"\uf006",
"\uf1b6",
"\uf1b7",
"\uf048",
"\uf051",
"\uf0f1",
"\uf249",
"\uf24a",
"\uf04d",
"\uf28d",
"\uf28e",
"\uf21d",
"\uf0cc",
"\uf1a4",
"\uf1a3",
"\uf12c",
"\uf239",
"\uf0f2",
"\uf185",
"\uf2dd",
"\uf12b",
"\uf1cd",
"\uf0ce",
"\uf10a",
"\uf0e4",
"\uf02b",
"\uf02c",
"\uf0ae",
"\uf1ba",
"\uf2c6",
"\uf26c",
"\uf1d5",
"\uf120",
"\uf034",
"\uf035",
"\uf00a",
"\uf009",
"\uf00b",
"\uf2b2",
"\uf2c7",
"\uf2cb",
"\uf2ca",
"\uf2c9",
"\uf2c8",
"\uf2c7",
"\uf2cb",
"\uf2c7",
"\uf2c9",
"\uf2ca",
"\uf2c8",
"\uf08d",
"\uf165",
"\uf088",
"\uf087",
"\uf164",
"\uf145",
"\uf00d",
"\uf057",
"\uf05c",
"\uf2d3",
"\uf2d4",
"\uf043",
"\uf150",
"\uf191",
"\uf204",
"\uf205",
"\uf152",
"\uf151",
"\uf25c",
"\uf238",
"\uf224",
"\uf225",
"\uf1f8",
"\uf014",
"\uf1bb",
"\uf181",
"\uf262",
"\uf091",
"\uf0d1",
"\uf195",
"\uf1e4",
"\uf173",
"\uf174",
"\uf195",
"\uf26c",
"\uf1e8",
"\uf099",
"\uf081",
"\uf0e9",
"\uf0cd",
"\uf0e2",
"\uf29a",
"\uf19c",
"\uf127",
"\uf09c",
"\uf13e",
"\uf0dc",
"\uf093",
"\uf287",
"\uf155",
"\uf007",
"\uf2bd",
"\uf2be",
"\uf0f0",
"\uf2c0",
"\uf234",
"\uf21b",
"\uf235",
"\uf0c0",
"\uf2bb",
"\uf2bc",
"\uf221",
"\uf226",
"\uf228",
"\uf237",
"\uf2a9",
"\uf2aa",
"\uf03d",
"\uf27d",
"\uf194",
"\uf1ca",
"\uf189",
"\uf2a0",
"\uf027",
"\uf026",
"\uf028",
"\uf071",
"\uf1d7",
"\uf18a",
"\uf1d7",
"\uf232",
"\uf193",
"\uf29b",
"\uf1eb",
"\uf266",
"\uf2d3",
"\uf2d4",
"\uf2d0",
"\uf2d1",
"\uf2d2",
"\uf17a",
"\uf159",
"\uf19a",
"\uf297",
"\uf2de",
"\uf298",
"\uf0ad",
"\uf168",
"\uf169",
"\uf23b",
"\uf1d4",
"\uf19e",
"\uf23b",
"\uf1d4",
"\uf1e9",
"\uf157",
"\uf2b1",
"\uf167",
"\uf16a",
"\uf166"
};
        #endregion


        public IconAwesomeSIZ()
        {
            InitializeComponent();
            this.SizeChanged += IconAwesomeSIZ_SizeChanged;
            Icono = AwesomeIcons.fa_android;

            this.txtIcono.FontFamily = new FontFamily(new Uri("pack://application:,,,/UserControlsSIZ;component/Resources/"), "./#FontAwesome");
        }

        private void IconAwesomeSIZ_SizeChanged(object sender, SizeChangedEventArgs e)
        {
            //txtIcono.FontSize = this.ActualHeight; // * 0.8;
            try
            {
                TextBlock tmp = txtIcono;
                //tmp.FontSize = e.NewSize.Height / tmp.FontFamily.LineSpacing;
                tmp.FontSize = (e.NewSize.Height - e.NewSize.Height * .06d) / tmp.FontFamily.LineSpacing;
            }
            catch { }
        }

        public AwesomeIcons Icono
        {
            get
            {
                int pos = Array.IndexOf(codigos, txtIcono.Text);
                return (AwesomeIcons)pos;
            }
            set
            {
                try
                {
                    txtIcono.Text = codigos[(int)value];
                }
                catch { }
            }
        }

        public Brush IconoBackground { get { return Background; } set { Background = value; } }

        public double IconoFontSize { get { return txtIcono.FontSize; } set { txtIcono.FontSize = value; } }

        public Brush IconoColor
        {
            get
            {
                //return (Brush)GetValue(IconoColorProperty);
                return txtIcono.Foreground;
            }
            set
            {
                txtIcono.Foreground = value;
                //SetValue(IconoColorProperty, value);

            }
        }

        public static readonly DependencyProperty IconoColorProperty =
        DependencyProperty.Register("IconoColor", typeof(Brush), typeof(IconAwesomeSIZ), new FrameworkPropertyMetadata(null, FrameworkPropertyMetadataOptions.BindsTwoWayByDefault, new PropertyChangedCallback(IconoColorChange)));

        private static void IconoColorChange(DependencyObject d, DependencyPropertyChangedEventArgs e)
        {
            try
            {
                var icono = d as IconAwesomeSIZ;
                icono.txtIcono.Foreground = (Brush)e.NewValue;
            }
            catch { }
        }


        //public static readonly DependencyProperty IconoFontSizeProperty =
        //DependencyProperty.Register("IconoFontSize", typeof(double), typeof(IconAwesomeSIZ), new FrameworkPropertyMetadata(null, FrameworkPropertyMetadataOptions.BindsTwoWayByDefault, new PropertyChangedCallback(IconoFontSizeChange)));

        //private static void IconoFontSizeChange(DependencyObject d, DependencyPropertyChangedEventArgs e)
        //{
        //    try
        //    {
        //        var icono = d as IconAwesomeSIZ;
        //        icono.txtIcono.FontSize = (double)e.NewValue;
        //    }
        //    catch { }
        //}

        //public static readonly DependencyProperty IconoProperty =
        //DependencyProperty.Register("Icono", typeof(AwesomeIcons), typeof(IconAwesomeSIZ), new FrameworkPropertyMetadata(null, FrameworkPropertyMetadataOptions.BindsTwoWayByDefault, new PropertyChangedCallback(IconoChange)));

        //private static void IconoChange(DependencyObject d, DependencyPropertyChangedEventArgs e)
        //{
        //    try
        //    {
        //        var icono = d as IconAwesomeSIZ;
        //        icono.txtIcono.Text = codigos[(int)(AwesomeIcons)e.NewValue];
        //    }
        //    catch { }
        //}

        public static readonly DependencyProperty IconoBackgroundProperty =
        DependencyProperty.Register("IconoBackground", typeof(Brush), typeof(IconAwesomeSIZ), new FrameworkPropertyMetadata(null, FrameworkPropertyMetadataOptions.BindsTwoWayByDefault, new PropertyChangedCallback(IconoBackgroundChange)));

        private static void IconoBackgroundChange(DependencyObject d, DependencyPropertyChangedEventArgs e)
        {
            var icono = d as IconAwesomeSIZ;
            icono.Background = (Brush)e.NewValue;
        }
        
    }
}
